<main id="main-container">
                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading">
                                Eventos <small>Listados de eventos dados de alta</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Eventos</li>
                                <li><a class="link-effect" href="">DataTables</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-content">
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <table class="table table-bordered table-striped js-dataTable-simple">
                                <thead>
                                    <tr>
                                        <th class="text-center">ID</th>
                                        <th>Nombre</th>
                                        <th class="hidden-xs">Fecha</th>
                                        <th class="hidden-xs" style="width: 15%;">Oficina</th>
                                        <th class="hidden-xs" style="width: 15%;">Cupo Maximo</th>
                                        <th class="hidden-xs" style="width: 15%;">Inscriptos</th>
                                        <th class="text-center" style="width: 10%;">Acci&oacute;n</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-center">1</td>
                                        <td class="font-w600">Evento 1</td>
                                        <td class="hidden-xs">23/08/2015</td>
                                        <td class="hidden-xs">Argentina</td>
                                        <td class="hidden-xs">50</td>
                                        <td class="hidden-xs"><a href="/usuarios/listado">25</a></td>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <button class="btn btn-xs btn-default" type="button" data-toggle="tooltip" title="Edit Client"><i class="fa fa-pencil"></i></button>
                                                <button class="btn btn-xs btn-default" type="button" data-toggle="tooltip" title="Remove Client"><i class="fa fa-times"></i></button>
                                            </div>
                                        </td>
                                    </tr>
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END Dynamic Table Simple -->
                </div>
                <!-- END Page Content -->
            </main>
            <!-- END Main Container -->