<section class="page-header page-header-modern bg-color-primary page-header-md ">
  <div class="container-fluid">
    <div class="row align-items-center">

      <div class="col">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <div class="overflow-hidden pb-2">
              <h1 class="text-light font-weight-bold text-9 appear-animation animated maskUp appear-animation-visible" data-appear-animation="maskUp" data-appear-animation-delay="100" style="animation-delay: 100ms;"><?php echo 'Playas' ?></h1>
            </div>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-md-center appear-animation animated fadeIn appear-animation-visible" data-appear-animation="fadeIn" data-appear-animation-delay="300" style="animation-delay: 300ms;">
              <li><a class="font-weight-semibold" href="/" style="color: #e2a522;font-size: 16px;">Inicio</a></span></li>
              <li><a class="active font-weight-semibold" href="/lugares" style="color: #e2a522;font-size: 16px;"></a></span> <i class="fa fa-angle-right"></i><span class="active " style="color: #e2a522;font-size: 16px;"> <?php echo 'Playas' ?></span></a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<!--==============================content=================================-->

<div class="container pt-3 pb-2">

  <div class="row pt-2">
    <div class="col">
      <!-- <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Playas</strong></h2> -->
    </div>
  </div>
  
  <div id="examples" class="container py-2">
    <div class="row">
      <div class="col-lg-4">
 <?php 
                        $coordenadasGoogleMaps =  "";
                        $i=0;
                        foreach ($this->cercanos as $key => $value) { 
                            $i=$i+1;
                            if($i%2==0)
                              {   
                            ?>
                             <ul class="list list-icons list-icons-style-3 list-primary list-icons-lg">
                            <li id="<?php echo $value["ce_keyword"]; ?>"><i class="fas fa-check"></i>
                                <a target="_blank" href="/playa/<?php echo $value["ce_keyword"]; ?>">
                                    <?php echo $value["ce_titulo"]; ?>
                                </a>
                            </li>
                              </ul>
                             <?php  } else  { ?>
                            <ul class="list list-icons list-icons-style-3 list-secondary list-icons-lg">
                            <li id="<?php echo $value["ce_keyword"]; ?>"><i class="fas fa-check"></i>
                                <a target="_blank" href="/playa/<?php echo $value["ce_keyword"]; ?>">
                                    <?php echo $value["ce_titulo"]; ?>
                                </a>
                            </li>
                              </ul>
                               <?php  } ?>
                        <?php 
                            if ($value["ce_googlemaps"] != ""){
                                $coordenadasGoogleMaps .= ($coordenadasGoogleMaps != "")?"##":"";
                                $coordenadas = explode(",",str_replace(")", "", str_replace("(", "", $value["ce_googlemaps"])));
                                $descripcion = ($value["ce_descripcion"] !="")?substr(strip_tags($value["ce_descripcion"]),0,100)."...":"";
                                $coordenadasGoogleMaps .= $coordenadas[1]."@@".$coordenadas[0]."@@".$value["ce_titulo"]."@@".$descripcion."@@".$value["ce_keyword"];
                            }
                        } ?>

                </div>
  </div>
</div>
<div class="row pt-2">
  <div class="col">
    <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Ubicación</strong></h2>
  </div>
  <div id="map_canvas" class="google-map mt-0 mb-0" style="height: 400px; position: relative; overflow: hidden;"><div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; background-color: rgb(229, 227, 223);"><div class="gm-err-container"><div class="gm-err-content"><div class="gm-err-icon"><img src="https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png" draggable="false" style="user-select: none;"></div><div class="gm-err-title">Se produjo un error.</div><div class="gm-err-message">Esta página no cargó bien Google Maps. Consulta la consola de JavaScript para obtener los detalles técnicos.</div></div></div></div></div>
</div>
</div>
</div>

        </div>
        
      </div>
    </div>
   <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">
var coordenadasGoogleMaps = '<?php echo $coordenadasGoogleMaps ?>';
var markersArray = new Array();
var map;
infos = [];
var infowindow = new google.maps.InfoWindow();
    var bounds = new google.maps.LatLngBounds();
    var myOptions = {
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.SATELLITE,
            disableDefaultUI: true
        }
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
verEnMapa();

function verEnMapa(){
    //Googlemaps
    var geocoder;
    var address;
    var myPano;
    var pLat;
    var pLong;
    var coordenadas = "";
    var marker;
    geocoder = new google.maps.Geocoder();
    ArraycoordenadasGoogleMaps =coordenadasGoogleMaps.split('##');
    var bounds = new google.maps.LatLngBounds();
    var imageBeneficio = new google.maps.MarkerImage('/css/images/iconos_sitio/Playas.png');

    for(var i =0; i < ArraycoordenadasGoogleMaps.length; i ++){
        coordenadas = ArraycoordenadasGoogleMaps[i].split("@@");

            pLong = coordenadas[0];
            pLat  = coordenadas[1];
            var point = new google.maps.LatLng(pLat, pLong, false);
                        bounds.extend(point);
                        var marker = new google.maps.Marker({
                                                                'position': point,
                                                                'bounds': true,
                                                                map: map,
                                                                'title' : coordenadas[2],
                                                                'identificador': coordenadas[4],
                                                                content:'<div style="width:300px;font-family:"Trebuchet MS", Arial, Helvetica, sans-serif"><a href="/playa/'+ coordenadas[4] +'" target="_blank" ><Strong>' + coordenadas[2] + '</Strong></a><br>'+ coordenadas[3] +'</div>',
                                                                'icon': imageBeneficio
                                                            });

                        pointGetCoord = point.toString().replace("(","").replace(")","");
                        pointGetCoord = pointGetCoord.split(",");
                        google.maps.event.addListener(marker, 'click', function() {
                                closeInfos();
                                seleccionarUbicacion(this.identificador);
                                var info = new google.maps.InfoWindow({content: this.content});
                                info.open(map,this);
                                infos[0]=info;
                            });
    }

            map.fitBounds(bounds);
}
function seleccionarUbicacion(identificador){
    $( "li" ).each(function( index ) {
        if (this.id)
        if ($('#' + this.id).attr('class') == 'seleccionadoEnMap'){
            $('#' + this.id).attr('class','');
        }
    });
    $('#identificador').attr('class','seleccionadoEnMap');

}
function closeInfos(){
 
   if(infos.length > 0){
 
      /* detach the info-window from the marker */
      infos[0].set("marker",null);
 
      /* and close it */
      infos[0].close();
 
      /* blank the array */
      infos.length = 0;
   }
}
</script>