<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>UbbiMap Login</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="../css/style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/js/jquery.cookie.js"></script>
</head>
<body>

<div id="main-popup" style="text-align:center;overflow-x:hidden;">
    <div class="col-md-12" >
    <img src="../img/logo2.png">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
   	 Ingrese la direcci&oacute;n donde quiere ir
    </div>
    <div class="col-md-12">
    <form id="form_georeferenciar">
        <div class="input-group">
          <span class="input-group-addon" style="font-size: 10px;display:block" id="basic-addon1">(ej. Armenia 2436, Capital Federal, Argentina)</span>
          <input type="text" class="form-control" name="direccion" id="direccion" placeholder="Armenia 2436, Capital Federal, Argentina" aria-describedby="basic-addon1">
        </div>
        <div class="input-group" style="margin: 10px 0px;text-align: right;width: 100%;"><input type="image" src="../img/cancelar.png">&nbsp;<input type="image" src="../img/inicio.png"></div>
    </form>
    </div>
    
</div>
<script type="text/javascript" src="/js/usuarioFunctions.js"></script>
</body>
</html>