<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>UbbiMap Login</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="../css/style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/js/jquery.cookie.js"></script>
</head>
<body>

<div id="main-popup" style="text-align:center;overflow-x:hidden;">
    <div class="col-md-12" >
    <img src="../img/logo2.png">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
    <img src="../img/soy_user.png" style="width:100%;">
    </div>
    <div class="col-md-12">
    <form id="sesion">
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">Usuario</span>
          <input type="text" class="form-control" name="usuario" placeholder="Mail con el que te registraste" aria-describedby="basic-addon1">
        </div>
        
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Contrase&ntilde;a</span>
          <input type="text" class="form-control" name="clave" placeholder="Ingres&aacute; tu clave" aria-describedby="basic-addon2">
        </div>
        <div class="col-lg-12">
            <div class="input-group">
              <span class="input-group-addon">
              mantenerme conectado
                <input type="checkbox" aria-label="...">
              </span>
            </div><!-- /input-group -->
 		 </div><!-- /.col-lg-6 -->
       <!-- 
         <div class="col-md-12" style="display: block;text-align: right;">Olvidaste tu contrase&ntilde;a?</div>
         <div class="col-md-12" style="display: block;text-align: right;">Olvidaste tu Usuario?</div>
          -->  
        <div class="input-group" style="margin: 10px 0px;text-align: right;width: 100%;"><input type="image" src="../img/cancelar.png">&nbsp;<input type="image" src="../img/inicio.png"></div>
    </form>
    </div>
    <div class="row">
    <div id="col-md-12" style="padding:10px 0px;"><img id="loginFbc" name="loginFbc" onmouseover="this.style.cursor='pointer';" src="../img/login-face.png"></div>
   <!-- <div id="col-md-12" style="padding:10px 0px;"><img onmouseover="this.style.cursor='pointer';" src="../img/login-twitter.png"></div> --> 
    </div>
    <div id="col-md-12" style="padding:20px 0px;">
    <img src="../img/new-user.png" style="width:100%;">
    </div>
    <div id="col-md-12" style="padding:20px 0px;">
    <a href="/persona/newuser" target="_self"><img src="../img/bot-registro.png"></a>
    </div>
</div>
<script type="text/javascript" src="/js/usuarioFunctions.js"></script>
</body>
</html>