<main id="main-container">
                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading">
                                Encuentas <small>Listados de encuestas</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Reportes</li>
                                <li><a class="link-effect" href="/usuarios/encuestas">encuestas</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-content">
                            <div class="row">
                                <div class="col-md-3">
                                    <select id="evento" name="ev" class="form-control">
                                      <option value="" >Seleccione evento</option>
                                    <?php foreach ($this->arrEventos as $e => $eValue) { ?>
                                        <?php if ( isset($_GET["ev"]) && ($eValue->getEv_id() == $_GET['ev']) ){ ?>
                                          <option value="<?php echo $eValue->getEv_id(); ?>" selected><?php echo $eValue->getEv_nombre(); ?></option>  
                                        <?php }else{ ?>
                                          <option value="<?php echo $eValue->getEv_id(); ?>" ><?php echo $eValue->getEv_nombre(); ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                    </select>
                                </div>
                                <div class="col-md-1">
                                    <center>
                                        <button class="btn btn-minw btn-default" id="filtro">Filtrar</button>
                                    </center>
                                </div>
                            </div><br>
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <div class="row">
                                <table id="tablas_selector" class="table table-bordered table-striped ">
                                    <thead>
                                        <tr>
                                            <th class="hidden-xs" style="width: 15%;">N°</th>
                                            <th class="hidden-xs">Usuario</th>
                                            <th class="hidden-xs" >Perspectiva</th>
                                            <th class="hidden-xs" style="width: 15%;">Oportunidades</th>
                                            <th class="hidden-xs" style="width: 15%;">Desafios</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <?php $existe2='';
                                        if ($this->arrUsuarios!= '') { ?>
                                            <?php if (count($this->arrEncuestas) > 0) { ?>
                                                <?php foreach ($this->arrEncuestas as $value) { 
                                                    $existe=''; ?>
                                                    <?php foreach ($this->arrUsuarios as $us) {
                                                        if($us->getUs_id() == $value->getUsuarios_us_id()){
                                                            $existe= 'ok';
                                                            $existe2= 'ok';
                                                            /*echo $existe.'1';*/
                                                        }
                                                    } 
                                                    /*echo $existe.'2';*/
                                                    if($existe == 'ok'){ ?>
                                                        <tr>
                                                            <td class="text-center"><?php echo $value->getEn_id();?></td>
                                                            <td class="text-center"><?php echo $value->getUsuarios_us_email(); ?></td>
                                                            <td class="text-center"><?php echo $value->getEn_perspectiva(); ?></td>
                                                            <td class="hidden-xs"><?php echo $value->getEn_oportunidades(); ?></td>
                                                            <td class="hidden-xs"><?php echo $value->getEn_desafios(); ?></td>
                                                        </tr>
                                                    
                                                <?php } } ?>
                                                <?php if($existe2 == ''){ ?>
                                                    <tr class="odd"><td valign="top" colspan="5" class="dataTables_empty">No data available in table</td></tr>
                                                <?php }  ?>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <?php if (count($this->arrEncuestas) > 0) { ?>
                                                <?php foreach ($this->arrEncuestas as $value) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $value->getEn_id();?></td>
                                                        <td class="text-center"><?php echo $value->getUsuarios_us_email(); ?></td>
                                                        <td class="text-center"><?php echo $value->getEn_perspectiva(); ?></td>
                                                        <td class="hidden-xs"><?php echo $value->getEn_oportunidades(); ?></td>
                                                        <td class="hidden-xs"><?php echo $value->getEn_desafios(); ?></td>
                                                    </tr>
                                               <?php } ?>
                                            <?php }else{ ?>
                                                <tr class="odd"><td valign="top" colspan="5" class="dataTables_empty">No data available in table</td></tr>
                                            <?php } 
                                        }   ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END Dynamic Table Simple -->
                </div>
                <!-- END Page Content -->
            </main>
            <!-- END Main Container -->
            <script>
            
            

            $('#filtro').click(function(event) {
                if ($('#evento').val() !='') {
                    window.location= "/usuarios/encuestas/?ev=" + $("#evento").val();
                };
            });
            
            </script>
            <style type="text/css">
            #filtro{
                width: 12%;
                border: 1px solid #BEBEBE;
                margin-left: 2%;
            }
            .leftdos{
                margin-left: 2%;   
            }
            #jerarquia{
                width: 264px;
            }
            .bottomuno{
                margin-bottom: 1%;
            }
            </style>