<main id="main-container">
                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading">
                                Reportes <small>Listados de usuarios</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Reportes</li>
                                <li><a class="link-effect" href="/usuarios/login">login</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-content">
                            <div class="row">
                                <div class="col-xs-4">
                                    <select id="usuario" name="us" class="form-control">
                                      <option value="">Seleccione usuario</option>
                                    <?php foreach ($this->arrUsuarios as $e => $uValue) { ?>
                                        <?php if ( isset($_GET["us"]) && ($uValue->getUS_id() == $_GET['us']) ){ ?>
                                            <option value="<?php echo $uValue->getUs_id(); ?>" selected><?php echo $uValue->getUs_nombre()."".$uValue->getUs_apellido(); ?></option>  
                                        <?php }else{ ?>
                                            <option value="<?php echo $uValue->getUs_id(); ?>"><?php echo $uValue->getUs_nombre()."".$uValue->getUs_apellido(); ?></option>  
                                        <?php } ?>
                                    <?php } ?>
                                    </select>
                                </div>
                                <div class="col-xs-4">
                                    <select id="evento" name="evento" class="form-control">
                                      <option value="" >Seleccione un evento</option>
                                    <?php foreach ($this->arrEventos as $e => $eValue) { ?>
                                        <?php if ( isset($_GET["ev"]) && ($eValue->getEv_id() == $_GET['ev']) ){ ?>
                                          <option value="<?php echo $eValue->getEv_id(); ?>" selected><?php echo $eValue->getEv_nombre(); ?></option>  
                                        <?php }else{ ?>
                                          <option value="<?php echo $eValue->getEv_id(); ?>" ><?php echo $eValue->getEv_nombre(); ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                    </select>
                                </div>
                                <div class="col-xs-4">
                                    <center>
                                        <button class="btn btn-minw btn-default" id="filtro">Filtrar</button>
                                    </center>
                                </div>
                            </div>
                            <!-- DataTables init on table by adding .js-dataTable-simple class, functionality initialized in js/pages/base_tables_datatables.js -->
                            <div class="row">
                                <table id="tablas_selector" class="table table-bordered table-striped js-dataTable-simple">
                                    <thead>
                                        <tr>
                                            <th class="text-center">ID</th>
                                            <th>Nombre</th>
                                            <th class="hidden-xs">Apellido</th>
                                            <th class="hidden-xs" style="width: 15%;">Tel&eacute;fono</th>
                                            <th class="hidden-xs" style="width: 15%;">Ultimo Login</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	<?php foreach ($this->usuarios as $value) { ?>
                                        <tr>
                                            <td class="text-center"><?php echo $value->getUs_id(); ?></td>
                                            <td class="font-w600"><?php echo $value->getUs_nombre(); ?></td>
                                            <td class="hidden-xs"><?php echo $value->getUs_apellido(); ?></td>
                                            <td class="hidden-xs"><?php echo $value->getUs_telefono(); ?></td>
                                            <td class="hidden-xs"><?php echo ($value->getUs_last_login() == 0)?"S/Login":$value->getUs_last_login(); ?></td>
                                        </tr>
                                       <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END Dynamic Table Simple -->
                </div>
                <!-- END Page Content -->
            </main>
            <!-- END Main Container -->
            <script>
            
            $('#select_all').change(function() {
                var checkboxes = $("#tablas_selector").find(':checkbox');
                if($(this).is(':checked')) {
                    checkboxes.prop('checked', true);
                } else {
                    checkboxes.prop('checked', false);
                }
            });

            $("#enviar_invitaciones").click(function(){
                var arrCheckbox = [];
                var i =0;
                $("#tablas_selector").find(':checkbox').each(function( index ) {
                    console.log($(this));
                    if($(this).is(':checked')) {
                        arrCheckbox[i] = $(this).val();
                        i ++;
                    }
                });
                if (arrCheckbox.length > 0){
                    $("#enviando").show();
                    var jqxhr = $.ajax( "/usuarios/enviarinvitaciones/ids/" + arrCheckbox.join(',') );
                     jqxhr.done(function(data) {
                         $("#enviando").hide();
                      })
                }else{
                    alert('Error, debe seleccionar algun usuario');
                }
            })

            $('#filtro').click(function(event) {
                if ($("#usuario").val() != '' && $('#evento').val() !='') {
                    window.location= "/usuarios/login/?us=" + $("#usuario").val()+ "&ev=" + $("#evento").val();
                };
                if ($("#usuario").val() != '' && $('#evento').val() =='') {
                    window.location= "/usuarios/login/?us=" + $("#usuario").val();
                };
                if ($("#usuario").val() == '' && $('#evento').val() !='') {
                    window.location= "/usuarios/login/?ev=" + $("#evento").val();
                };
                if ($("#usuario").val() == '' && $('#evento').val() =='') {
                    window.location= "/usuarios/login";  
                };
                /*$.ajax({
                    url: "/usuarios/listado/?j=" + $("#jerarquia").val()+ "&a=" + $("#actividad").val(), // Url to which the request is send
                    type: "POST",             // Type of request to be send, called as method
                    data:  dataString,// Data sent to server, a set of key/value pairs (i.e. form fields and values)
                    success: function(data)   // A function to be called if request succeeds
                    {
                        if(data!= ''){
                            jQuery( "#mensajeOK" ).show();
                            var new_position = jQuery('.page-heading').offset();
                            window.scrollTo(new_position.left,new_position.top);
                        }
                        else {
                            jQuery( "#mensajeERROR" ).show();
                            var new_position = jQuery('.page-heading').offset();
                            window.scrollTo(new_position.left,new_position.top);
                        }
                    }
                })*/
                //window.location= "/usuarios/listado/?j=" + $("#jerarquia").val()+ "&a=" + $("#actividad").val();
            });
            function eliminarUsuario(id){
            	if (confirm('Esta seguro?')){
	            	var jqxhr = $.ajax( "/usuarios/eliminar/id/" + id );
			       	 jqxhr.done(function(data) {
			       		 var obj = jQuery.parseJSON(data);
			       		 console.log(obj.proceso);
			       		 if (obj.proceso != "error"){
			       		 	document.location.reload();
			       		 }else{
			       			jQuery( "#mensajeERROR" ).show();
			           		var new_position = jQuery('.page-heading').offset();
			           		window.scrollTo(new_position.left,new_position.top);
			           	 }
			       	  })
			       	  jqxhr.fail(function() {
			       		  jQuery( "#mensajeERROR" ).show();
			       	  });
            	}
            }
            </script>
            <style type="text/css">
            #filtro{
                width: 12%;
                border: 1px solid #BEBEBE;
                margin-left: 2%;
            }
            .leftdos{
                margin-left: 2%;   
            }
            #jerarquia{
                width: 264px;
            }
            .bottomuno{
                margin-bottom: 1%;
            }
            </style>