<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <title>Turtech</title>
  </head>

  <body style="margin:0 auto; width:595px; padding:0">
    <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="595px">
      <tbody>
        <!-- Header -->
        <tr bgcolor="#9DCCF5" style="background-image:url(<?php echo RUTA; ?>images/header-texture.jpg">
          <td width="223px">
            <img src="<?php echo RUTA; ?>images/223x67.png" width="223px" height="67px">
          </td>
          <td width="205px">
            <img src="<?php echo RUTA; ?>images/turtech-logo.png" width="205px" height="67px">
          </td>
          <td bgcolor="#9DCCF5">
            <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="152px">
              <tbody>
                <tr height="15px">
                  <td>
                  <img src="<?php echo RUTA; ?>images/152x16.png" width="152px" height="16px">
                  </td>
                </tr>
                <tr bgcolor="#93193a">
                  <td align="center" width="51px" height="52px" style="padding:12px 0 13px 0;">
                    <p style="font-family:arial;color:#9DCCF5;font-size:12px;font-weight:bolder;letter-spacing:-0.5px;margin:0;">
                      28 de Septiembre de 2015
                    </p>
                    <p style="font-family:arial;color:#FFF;font-size:9px;font-weight:bolder;margin:0; letter-spacing:-0.5px;">
                      Feria Internacional de Turismo - FIT
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td bgcolor="#9DCCF5" width="16px">
            <img src="<?php echo RUTA; ?>images/16x1.png" width="16px" height="1px">
          </td>
        </tr>
        <!--//Header  -->

        <!-- Contenido -->
        <tr>
          <td colspan="4">
            <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="595px">
              <tbody>
                <!-- Espacio Top -->
                <tr>
                  <td colspan="3">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
                <!-- //Espacio Top -->
                <tr>
                  <td>
                    <img src="<?php echo RUTA; ?>images/20x1.png" width="20px" height="1px">
                  </td>
                  <td width="555px">
                    <h1 style="font-family:arial;color:#333;font-size:14px;font-weight:bolder;margin:0;">
                      Hola <?php echo $this->nombre; ?>, <?php echo  $this->apellido; ?>
                    </h1>
                    <p style="font-family:arial;color:#666;font-size:14px;margin:0;">
                    Tu registraci&oacute;n se ha realizado correctamente.<br>
                    Tus datos para ingresar son los siguientes:<br>
                    Usuario: <?php echo $this->usuario; ?><br>
                    Contrase&ntilde;a: <?php echo $this->pass; ?><br> Muchas gracias.</p>
                  </td>
                  <td>
                    <img src="<?php echo RUTA; ?>images/20x1.png" width="20px" height="1px">
                  </td>
                </tr>
                <!-- Espacio Bottom -->
                <tr>
                  <td colspan="3">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
                <!-- //Espacio Bottom -->
              </tbody>
            </table>
          </td>
        </tr>
        <!--//Contenido  -->

        <!-- Patrocinantes Fila 1 -->
        <tr height="57px">
          <td colspan="4">
            <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="595px">
              <tbody>
                <tr height="12px">
                  <td colspan="14">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
                <tr>
                  <td width="110px">
                    <p align="right" style="font-family:arial;color:#93193a;font-size:10px;font-weight:bolder;letter-spacing:-0.5px;margin:0;text-transform:uppercase;">
                      MAIN SPONSORS&nbsp;&nbsp;
                    </p>
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-main-01-48x43.jpg" width="48px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-main-02-48x43.jpg" width="48px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-main-01-48x43.jpg" width="48px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-main-02-48x43.jpg" width="48px" height="43px">
                  </td>
                  <td width="58px">
                    <p align="right" style="font-family:arial;color:#93193a;font-size:10px;font-weight:bolder;letter-spacing:-0.5px;margin:0;text-transform:uppercase;">
                      PREMIUM&nbsp;&nbsp;
                    </p>
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-premium-01-38x43.jpg" width="38px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-premium-02-38x43.jpg" width="38px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-premium-01-38x43.jpg" width="38px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-premium-02-38x43.jpg" width="38px" height="43px">
                  </td>
                  <td width="48px">
                    <img src="<?php echo RUTA; ?>images/logo-premium-01-38x43.jpg" width="38px" height="43px">
                  </td>
                  <td width="30px">
                  <img src="<?php echo RUTA; ?>images/30x1.png" width="30px" height="1px">
                  </td>
                </tr>
                <tr height="12px">
                  <td colspan="14">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <!--//Patrocinantes Fila 1  -->

        <!-- Patrocinantes Fila 2 -->
        <tr height="57px">
          <td colspan="4">
            <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="595px">
              <tbody>
                <tr>
                  <td width="86px">
                    <p align="right" style="font-family:arial;color:#93193a;font-size:10px;font-weight:bolder;letter-spacing:-0.5px;margin:0;text-transform:uppercase;">
                      GOLD&nbsp;&nbsp;
                    </p>
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-01-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-02-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-01-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-02-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-01-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="31px">
                    <img src="<?php echo RUTA; ?>images/logo-gold-02-31x29.jpg" width="31px" height="29px">
                  </td>
                  <td width="72px">
                    <p align="right" style="font-family:arial;color:#93193a;font-size:10px;font-weight:bolder;letter-spacing:-0.5px;margin:0;text-transform:uppercase;">
                      SUPPORTERS&nbsp;&nbsp;
                    </p>
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-01-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-02-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-01-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-02-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-01-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-02-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/logo-support-01-27x29.jpg" width="27px" height="29px">
                  </td>
                  <td width="27px">
                    <img src="<?php echo RUTA; ?>images/30x1.png" width="30px" height="1px">
                  </td>
                </tr>
                <tr height="13px">
                  <td colspan="16">&nbsp;
                    
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <!--//Patrocinantes Fila 2  -->

        <!-- FOOTER -->
        <tr bgcolor="#b3b5b7">
          <td colspan="6">
            <table border="0" cellspacing="0" cellpadding="0" align="center" borderspacing="0" width="595px">
              <tbody>
                <tr height="12px">
                  <td colspan="6">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
                <tr>
                  <td width="46px">
                    <img src="<?php echo RUTA; ?>images/46x1.png" width="46px" height="1px">
                  </td>
                  <td width="148px" valign="top">
                    <h1 style="font-family:arial;color:#FFF;font-size:14px;font-weight:bolder;margin:0;">
                      CUANDO
                    </h1>
                    <a href="mailto:info@turtech.com.ar" style="font-family:arial;color:#FFF;font-size:11px;font-weight:bolder;margin:0;">
                      <?php $fecha_comienzo = substr($this->arrDbTableEvento->getEv_fecha_comienzo(),6,2);
                            $fecha_fin = substr($this->arrDbTableEvento->getEv_fecha_fin(),6,2);  ?>
                      <?php 
                      if ($fecha_fin - $fecha_comienzo > 1){
                        echo "Del ".$fecha_comienzo." al ".$fecha_fin." ";
                      }else{
                        for ($i = $fecha_comienzo; $i <= $fecha_fin; $i++) {
                          echo ($i == $fecha_fin)?$i:$i." & ";
                        }
                      }?>
                      de Septiembre<br>20<?php echo substr($this->arrDbTableEvento->getEv_fecha_fin(),0,2);?>
                    </a>
                    <!-- <p style="font-family:arial;color:#FFF;font-size:11px;font-weight:bolder;margin:0;">
                      [+54] 11 4701 0999
                    </p>
                    <p style="font-family:arial;color:#FFF;font-size:11px;font-weight:bolder;margin:0;">
                      Arias 1691 Nu&ntilde;ez 2A [C.P. 1429]
                      <br>
                      <br>
                      Buenos Aires, Argentina 
                    </p> -->
                  </td>
                  <td width="20px">
                  <img src="<?php echo RUTA; ?>images/20x1.png" width="20px" height="1px">
                  </td>
                  <td width="218px" valign="top">
                    <h1 style="font-family:arial;color:#FFF;font-size:14px;font-weight:bolder;margin:0;">
                      DONDE
                    </h1>
                    <p style="font-family:arial;color:#FFF;font-size:11px;font-weight:bolder;margin:0;">
                    <?php echo utf8_decode($this->arrDbTableEvento->getEv_titulo_ubicacion())."<br />"?>
                    </p>
                  </td>
                  <td width="20px">
                  <img src="<?php echo RUTA; ?>images/20x1.png" width="20px" height="1px">
                  </td>
                  <td width="200px" valign="top">
                    <h1 style="font-family:arial;color:#FFF;font-size:14px;font-weight:bolder;margin:0;">
                      CONTACTANOS
                    </h1>
                    
                    <?php $info = explode(",", $this->arrDbTableEvento->getEv_email_responsable()); ?>
                    <?php foreach ($info as $value) { ?>
                      <a href="mailto:<?php echo utf8_decode($value); ?>" style="font-family:arial;color:#FFF;font-size:11px;font-weight:bolder;margin:0;"><?php echo utf8_decode($value); ?></a><br>
                    <?php  } ?>
                  </td>
                </tr>
                <tr height="12px">
                  <td colspan="6">
                    <img src="<?php echo RUTA; ?>images/595x12.png" width="595px" height="12px">
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
        <!--//FOOTER -->
      </tbody>
    </table>
  </body>
</html>