<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>UbbiMap Login</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="../css/style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>
<body>

<div id="main-popup" style="text-align:center;overflow-x:hidden;">
    <div class="col-md-12" >
    <img src="../img/logo2.png">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
    <img src="../img/crear-cuenta3.png" style="width:100%;">
    </div>
    <div class="col-md-12">
    <form>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">Nombre de la Empresa</span>
          <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
        </div>
        
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Razon social</span>
          <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
          <span class="input-group-addon" id="basic-addon2">Cuil</span>
          <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
        </div>
        
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Direccion del local</span>
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
        </div>
        
        <div class="input-group">
         <span class="input-group-addon" id="basic-addon2">Ciudad</span>
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
           <span class="input-group-addon" id="basic-addon2">Prov</span>
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
        <span class="input-group-addon" id="basic-addon2">País</span>
          <select class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
           </select>
        </div>
        
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Telefono con codigo de area</span>
             <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2" style="width:50px;">
              <span class="input-group-addon" id="sizing-addon1"> - </span>
              <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon1">
			</div>
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Mail de contacto</span>
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
        </div>  
            
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Pagina Web</span>
         
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
        </div>  
         
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Horario de atencion</span>
          <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
        </div>  
           
        <div class="input-group">
        <span class="input-group-addon" id="basic-addon2">Logo de la empresa</span>
        <input type="file" class="form-control" placeholder="" aria-describedby="basic-addon2">
        </div>     
         
         <span class="detalle">los archivos no deben pesar mas de x peso y x pixeles</span>
         
        <div class="input-group" style="margin: 10px 0px;text-align: right;width: 100%;"><input type="image" src="../img/cancelar.png">&nbsp;<input type="image" src="../img/config-emp.png"></div>
    </form>
    </div>
   <div class="col-md-12" style="text-align:right;margin-top: 26px;">
   <div class="col-md-2" style="float: left;"><a href="new-user.html" target="_self"><img src="../img/atras.png"></a></div>
   <div class="col-md-10" style="text-align:right;margin-top: -12px;">
   <div class="checkbox">
    <label>
      <input type="checkbox">He leido y acepto los terminos de privacidad. <a href="#" target="_blank">Leer...</a>
    </label>
  </div></div>
   </div>
</div>
</body>
</html>
