<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>UbbiMap Login</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="../css/style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>
<body>

<div id="main-popup" style="text-align:center;overflow-x:hidden;">
    <div class="col-md-12" >
    <img src="../img/logo2.png">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
    <img src="../img/soy_user.png" style="width:100%;">
    </div>
    <div class="row">
    <div class="col-md-12" style="padding:20px;display:block; text-align:center">
    GRACIAS POR REGISTRARSE EN UBIMAP.<BR>
    configura tu anuncio y palabras claves para que te encuentren. <br>!No vas a estar solo¡ Preparamos tutoriales para hacer mas facil tu experiencia.
    </div>
    <div class="col-md-6" style="padding:10px 0px;display: inline;"><img src="../img/tutorial.png"></div>
    <div class="col-md-6" style="padding:10px 0px;display: inline;"><a href="new-emp.html"><img src="../img/config.png"></a></div>
    </div>
    
</div>
</body>
</html>
