<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>UbbiMap Login</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="../css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="../css/style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

</head>
<body>

<div id="main-popup" style="text-align:center;overflow-x:hidden;">
    <div class="col-md-12">
    <img src="../img/logo2.png">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
    <img src="../img/new-user.png" style="width:100%;">
    </div>
    <div class="col-md-12" style="padding:20px 0px;">
            <div class="col-md-3" style="width:25%;float:left;"><p style="margin-top: 70px;"><strong>Empresa:</strong></p></div>
            <div class="col-md-9" style="width:50%;float:left;">
                    <div class="col-md-12"><a href="form-emp.html"><img src="../img/empresa.png"></a><br>
                    <p style="padding:10px 0px;width: 309px;text-align: left;font-size: 13px;">¿Sos un sucursal de las empresa? tambien podes registrate¡ Segui por aca y dale de alta ahora.</p>
                    </div>
                    <div class="col-md-12" ><a href="form-emp.html"><img src="../img/franquisia.png"></a><br>
                    <p style="padding:10px 0px;width: 309px;text-align: left;font-size: 13px;">¿Sos una franquicia? Tambien podes registrarte.!Comenza ahora¡</p>
                    </div>
            </div>
    </div>
    <div class="col-md-12">
                    <p style="padding:10px 0px;width: 100%;text-align: center;font-size: 13px;border-bottom:1px solid #ccc; display:inline-block;">
                    Podes utilizar todos los servicios de ubimap.com, mientras enviamos tus datos a evaluar con el titulo de la cuenta ya registrada de la empresa.Te pedimos disculpa por las molestias
                    
                    </p>
                    </div>
    <div class="col-md-3" style="float: left;"><a href="log.html" target="_self"><img src="../img/atras.png"></a></div>
</div>
</body>
</html>
