<section class="mainSection">
      <div class="wrapper wrapperSection clearfix">
        <section class="sidebar">
            <div class="box">
                <div class="innerBox">
                    <h3>Restaurantes y Confiter&iacute;as</h3>
                    <ul class="listadoMapa">
                        <?php 
                        $coordenadasGoogleMaps =  "";
                        foreach ($this->cercanos as $key => $value) { ?>
                            <li id="<?php echo $value["go_keyword"]; ?>">
                                <a href="/restaurantes-y-confiterias/<?php echo $value["go_keyword"]; ?>">
                                    <span class="nombre"><?php echo $value["go_titulo"]; ?></span>
                                </a>
                                    <!-- <span class="categoria">Desayunos Gourmet</span>-->
                                    <p><?php echo substr(strip_tags($value["go_descripcion"]),0,100)."..."; ?></p>
                            </li>
                        <?php 
                            if ($value["go_googlemaps"] != ""){
                                $coordenadasGoogleMaps .= ($coordenadasGoogleMaps != "")?"##":"";
                                $coordenadas = explode(",",str_replace(")", "", str_replace("(", "", $value["go_googlemaps"])));
                                $coordenadasGoogleMaps .= $coordenadas[1]."@@".$coordenadas[0]."@@".$value["go_titulo"]."@@".substr(strip_tags($value["go_descripcion"]),0,100)."..."."@@".$value["go_keyword"];
                            }
                        } ?>
                    </ul>
                </div>
            </div>
            <!-- /box -->
            <div class="bannerContacto">
                <a href="/contacto"><img src="/css/images/banner-contacto.gif" alt="Contactenos" title ="Contactenos"></a>
            </div>
        </section>
        <!-- /sidebar -->
        <section class="mainCol">
            <h2>Ubicaci&oacute;n</h2>
            <div class="contenedorMapa">
                <div id="map_canvas" style="width:624px;height: 624px;" ></div>
            </div>
            <div>
                <img src="/css/images/banner.jpg" alt="">
            </div>
        </section>
        <!-- /mainCol -->
      </div>
    </section>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">
var coordenadasGoogleMaps = '<?php echo $coordenadasGoogleMaps ?>';
var markersArray = new Array();
var map;
infos = [];
var infowindow = new google.maps.InfoWindow();
    var bounds = new google.maps.LatLngBounds();
    var myOptions = {
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.SATELLITE,
            disableDefaultUI: true
        }
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
verEnMapa();

function verEnMapa(){
    //Googlemaps
    var geocoder;
    var address;
    var myPano;
    var pLat;
    var pLong;
    var coordenadas = "";
    var marker;
    geocoder = new google.maps.Geocoder();
    ArraycoordenadasGoogleMaps =coordenadasGoogleMaps.split('##');
    var bounds = new google.maps.LatLngBounds();
    var imageBeneficio = new google.maps.MarkerImage('/css/images/iconos_sitio/Restaurantes.png');

    for(var i =0; i < ArraycoordenadasGoogleMaps.length; i ++){
        coordenadas = ArraycoordenadasGoogleMaps[i].split("@@");

            pLong = coordenadas[0];
            pLat  = coordenadas[1];
            var point = new google.maps.LatLng(pLat, pLong, false);
                        bounds.extend(point);
                        var marker = new google.maps.Marker({
                                                                'position': point,
                                                                'bounds': true,
                                                                map: map,
                                                                'title' : coordenadas[2],
                                                                'identificador': coordenadas[4],
                                                                content:'<div style="width:560px;font-family:"Trebuchet MS", Arial, Helvetica, sans-serif"><h1><Strong>' + coordenadas[2] + '</Strong></h1><br>'+ coordenadas[3] +'<br></div>',
                                                                'icon': imageBeneficio
                                                            });

                        pointGetCoord = point.toString().replace("(","").replace(")","");
                        pointGetCoord = pointGetCoord.split(",");
                        google.maps.event.addListener(marker, 'click', function() {
                                closeInfos();
                                seleccionarUbicacion(this.identificador);
                                var info = new google.maps.InfoWindow({content: this.content});
                                info.open(map,this);
                                infos[0]=info;
                            });
    }

            map.fitBounds(bounds);
}
function seleccionarUbicacion(identificador){
    $( "li" ).each(function( index ) {
        if (this.id)
        if ($('#' + this.id).attr('class') == 'seleccionadoEnMap'){
            $('#' + this.id).attr('class','');
        }
    });
    $('#' + identificador).attr('class','seleccionadoEnMap');

}
function closeInfos(){
 
   if(infos.length > 0){
 
      /* detach the info-window from the marker */
      infos[0].set("marker",null);
 
      /* and close it */
      infos[0].close();
 
      /* blank the array */
      infos.length = 0;
   }
}
</script>