<div id="content">   
  <div class="row-title">
    <div class="container">
      <h2>COLONIA DEPORTIVA RECREATIVA 2020</h2>
      <div class="breadcrumb"> <span><a href="/">Inicio</a></span> <i class="fa fa-angle-right"></i><span>Contacto</div>
    </div>
  </div>
  <div class="container">
    <div class="row content-div v_contact_form2 v_contact_form m_sm_bottom_20">
      <article class="span6">
        <form id="contactform" class="post_form v_form form-horizontal m_b_no_space">
          
          <h3>Formulario</h3>  
          <ul>
            <li class="clearfix">
              <h3>Datos Personales</h3>  
            </li>
            <li class="clearfix">
              <ul class="v_h_fild">
                <li>                 
                  <div class="full_width">
                    <input type="text" id="cf_edad" name="deForm" placeholder="Edad (de 6 a 13 años)" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="email" id="cf_email" name="correoForm" placeholder="Apellido y Nombre" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Dirección" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="D.N.I No:" class="full_width">
                  </div>
                </li> 
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="F. de Nac:" class="full_width">
                  </div>
                </li>
              </ul>
            </li>
            <li class="clearfix">
              <h3>Datos del Padre/Madre/Tutor</h3>  
            </li>
            <li class="clearfix">
              <ul class="v_h_fild">
                <li>
                  <div class="full_width">
                    <input type="email" id="cf_email" name="correoForm" placeholder="Apellido y Nombre" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Dirección" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="D.N.I No:" class="full_width">
                  </div>
                </li> 
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Telefonos de
Emergencia 1" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Telefonos de
Emergencia 2" class="full_width">
                  </div>
                </li>
              </ul>
            </li>
            <li class="clearfix">
              <h3>Datos de Salud</h3>  
            </li>
            <li class="clearfix">
              <ul class="v_h_fild">
                <li>
                  <div class="full_width">
                    <input type="email" id="cf_email" name="correoForm" placeholder="Grupo Sanguíneo" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <label>Alérgico a algún medicamento? Cual?</label>
                    <input type="checkbox" name="Si_medicamento" >&nbsp;S&iacute;
                    <input type="checkbox" name="No_medicamento" >&nbsp;No;
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Cual ?" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="D.N.I No:" class="full_width">
                  </div>
                </li> 
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Telefonos de
Emergencia 1" class="full_width">
                  </div>
                </li>
                <li>
                  <div class="full_width">
                    <input type="text" id="cf_subject" name="asuntoForm" placeholder="Telefonos de
Emergencia 2" class="full_width">
                  </div>
                </li>
              </ul>
            </li>
            <li class="clearfix">
              <textarea id="cf_message" name="mensajeForm" placeholder="Mensaje"></textarea>
            </li>
            <li class="clearfix">
              <label class="control-label" for="capcha">Anti-spam test: 4 + 4 =</label>
              <div class="fleft third_column">
                <input type="text" id="capcha" name="" class="full_width">
              </div>
            </li>
            <li class="clearfix">
              <button class="btn-small">Inscribirme</button>
            </li>
          </ul>
        </form>
      </article>
      <article class="span6">
        <h3>Informaci&oacute;n de contacto</h3> 
        <div class="row">
          <ul class="row v_drop extra-marg m_xm_bottom_20">
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-map-marker"></i></span></a>
                <p class="txt-2">Balneario El Condor, Rio Negro <br>
                  C.P. 8501</p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  <a href="mailto:contacto@balneario-el-condor.com.ar">contacto@balneario-el-condor.com.ar</a> <br>
                  
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3 ms_p_bottom_10">
          <section class="block-features">
              <div><a href="#"><span><i class="fa fa-phone"></i></span></a>
                <p class="txt-2">
                  Contacto Web <br>
                  2920 - 535353<br>
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-wrench"></i></span></a>
                <p class="txt-2">
                  <a href="http://viedma.gov.ar/index.php/el-condor">Municipalidad del Condor</a> <br>
                  <a href="http://viedma.gov.ar/turismo/">Turismo Viedma</a>
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Centro de Salud<br>
                  107 <br>
                  2920 - 497198 <br>
                  Urgencias: 15414693
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Bomberos<br>
                  100 <br>
                  2920 - 497161
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Comisaria<br>
                  101 <br>
                  2920 - 497300
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3" style="margin-top:-13%;">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Escuela N° 246<br>
                  2920 - 497055
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Aguas Rionegrinas<br>
                  0800-999-24827
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Edersa (Luz)<br>
                  0800-222-9500
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Fauna<br>
                  2920 - 423391 <br>
                  2920 - 422282
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Camuzzi<br>
                  0810-555-3698<br>
                  Viedma 2920 - 426451 <br>
                  Emergencias: 0810-999-0810
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Biblioteca Popular<br>
                  2920 - 15343779    
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Defensa Civil<br>
                  103
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Delegaci&oacute;n Municipal<br>
                  2920 - 497068
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Informes Tur&iacute;sticos<br>
                  2920 - 497148
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Prefectura Naval Argentina<br>
                  106 <br>
                  2920 - 461742 <br>
                  2920 - 464918
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Farmacia<br>
                  2920 - 497176
                  <br><br><br><br>
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Terminal de Omnibus<br>
                  2920 - 497209
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Cami&oacute;n Atmosf&eacute;rico<br>
                  2920 - 15564042
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>

          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Recolector de Escombros y Ramas<br>
                  Fletes y Mudanzas <br>
                  2920 - 15360233
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
          <li class="span3">
            <section class="block-features">
              <div><a href="#"><span><i class="fa fa-envelope"></i></span></a>
                <p class="txt-2">
                  Servicio de Grua Privado <br>
                  para el Autom&oacute;vil<br>
                  2920 - 15359421<br>
                  2920 - 15260928<br>
                  2920 - 15605458
                </p>
              </div>
              <div class="clearfix"></div>
            </section>
          </li>
        </ul>
        </div>
      </articl
    </div>         
  </div>    
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>

<script type="text/javascript">
    var initialLocation;
    var browserSupportFlag =  new Boolean();
    var map;
    var infowindow = new google.maps.InfoWindow();
    var latitud  = '-41.0414809';
    var longitud = '-62.8291098';
    var myOptions = {
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.SATELLITE
        };
        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      

        initialLocation = new google.maps.LatLng(latitud,longitud);
        contentString = "Balneario El Condor";
        map.setCenter(initialLocation);
        infowindow.setContent(contentString);
        infowindow.setPosition(initialLocation);
        infowindow.open(map);
</script>