<div  itemscope itemtype=" http://schema.org/NewsArticle" class="wrapper wrapperSection clearfix">
        <section class="mainCol left long colNota" style="margin-top:20px;width:970px">
            <h1 style="width:980px;margin-bottom:20px;">SEMANA DE ARTISTAS LOCALES EN EL ESCENARIO DE EL C&Oacute;NDOR</h1>
            <div itemprop="description">
            <p style="text-align:justify">Desde ma&ntilde;ana martes 20 de enero, El C&oacute;ndor vivir&aacute; cuatro jornadas de recitales gratuitos de artistas locales, en el escenario permanente ubicado en la playa.<br><br>

M&aacute;s de 45 bandas y solistas, con m&aacute;s de 200 artistas locales en escena, dar&aacute;n un marco distinto a la Fiesta del Mar y el Acampante. <br><br>

Las bandas locales contar&aacute;n con la puesta esc&eacute;nica y t&eacute;cnica similar a la solicitada por los grupos de trascendencia nacional.<br><br>

Las jornadas se completar&aacute;n el viernes con la actuaci&oacute;n de Miranda y el s&aacute;bado con la elecci&oacute;n de la reina y el show de fuegos artificiales.<br><br>Fuente: Turismo Viedma.</p></div>
<img src="/imagenes/artistas-bandas-locales-el-condor.jpg">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=116725188535269";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-comments" data-href="http://www.balneario-el-condor.com.ar/artistas-locales-20-21-22-23-24-25" data-width="970" data-numposts="5" data-colorscheme="light"></div>
</section>
