<section class="mainSection">
      <div class="wrapper wrapperSection clearfix">
        <section class="fullCol">
        	<h2>5ta Fiesta Nacional del Tejo - Club de Amigos Balneario El C&oacute;ndor</h2>
            <div class="datosBalneario" style="float:right;">
            	<ul style="width:400px">
                	<li>
                    	<p><span class="titulo"style="font-size: 18px;">Cronograma:</span></p>
                    </li>
                    <li><strong>Jueves 13 de marzo (Programa Oficial)</strong><br><br>
						- 11:00 hs, Disponibilidad de canchas para practicas y entrenamiento<br><i>(todo el d&iacute;a)</i><br>
						- 14:30 hs, Libre para Paseos<br>
						- 16:00 hs, Clinica de tecnicas y tacticas de Tejo<br>
						- 20:30 hs Libre para cena<br>
						</li>
						<li><strong>Viernes 14 de marzo (Programa Oficial)</strong><br><br>
						- 10:00 hs, Apertura mesas de inscripcion Copa Oro<br>
						- 10:15 hs, Apertura mesa de Inscripcion, Torneo Nacional de Trios, de edad libre para damas y caballeros.<br>
						- 11:00 hs, Reunion Anual de Dirigentes de Clubes de Tejo<br>
						- 12:30 hs, Libre para Almuerzo o Paseos Programados.<br>
						- 14:30 hs, Charla sobre integraci&oacute;n grupal.<br>
						- 15:30 hs, Comienzo de la Copa Oro entre los 8 clubes clasificados<br>
						- 19:00 hs, Entrega de Premios Copa de Oro<br>
						- 20:30 hs Libre para Cena<br>
						</li>
						 <li><strong>Sabado 15 de Marzo (Programa Oficial)</strong><br><br>
						
						- 09:00 hs, Comienzo del Torneo nacional de Trios 5ta Fiesta Nacional del Tejo.<br>
						- 13:00 hs, Almuerzo In-situ (puestos y bares del Club)<br>
						- 20:30 hs, Cena en el Club de Amigos. Premiaci&oacute;n a los top Ten (a cargo de c/u)<br>
						- 22:30 hs, Baile, Show. sorteos carnaval carioca, etc.<br>
						</li>
 						<li><strong>Domingo 16 de Marzo (Programa Oficial)</strong><br><br>
						
						- 10:00 hs, Continua el Torneo Nacional de Trios 5ta Fiesta Nacional del Tejo<br>
						- 13:00 hs, Almuerzo In-situ (puestos y bares del Club)<br>
						- 17:00 hs, Entrega de Premios Torneo Nacional de Trios 5ta Fiesta Nacional<br>
						</li>
						<li><strong>Lunes 17 de Marzo (Programa Optativo)</strong><br><br>
						
						- 11:00 hs, Torneo a la bolsa Copa Club de Amigos del B. El Condor<br>
						- 11:30 hs, Paseos Turisticos<br>
						- 17:00 hs, Entrega de Premios Torneo Balneario El Condor<br><br>
						<strong>ALOJAMIENTOS PAGOS EN HOTELES-DEPARTAMENTOS Y BUNGALOS</strong><br>
						<li>
                </ul>
            </div>
            <div class="contenedorForm" style="float:left;">
            	<span class="titulo" style="font-size:18px;" >Completa tus datos y te ayudamos con tu estad&iacute;a</span>
            	<span class="titulo" style="color: black;"><strong>Datos Personales</strong></span>
                <form name="AltaFormulario" id="AltaFormulario" >
                	<dl>
                    	<dt><label for="nombre">* Nombre:</label></dt>
                        <dd><input type="text" id="nombre" name="nombre"></dd>
                        <dt><label for="apellido">* Apellido:</label></dt>
                        <dd><input type="text" id="apellido" name="apellido"></dd>
                        <dt><label for="telefono">* Tel&eacute;fono de contacto:</label></dt>
                        <dd><input type="text" id="telefono" name="telefono"></dd>
                        <dt><label for="mail">* Direcci&oacute;n de Correo de contacto:</label></dt>
                        <dd><input type="text" id="mail" name="mail"><br></dd>
                        <dt><label for="deForm"><input type="checkbox" value="1" checked="true" name="quiero" id="quiero" />&nbsp;Quiero que me envien informaci&oacute;n del la web del balneario.</label><br><br></dt>
						<dt><label for="nombre">* Nombre del Club o Asociaci&oacute;n a la cual representa:</label></dt>
                        <dd><input type="text" id="nombreclub" name="nombreclub"></dd>
                        
                        <dt><label for="mail">Provincia:</label></dt>
                        <dd><select name="provincia" id="provincia">
                            	<option value='Buenos Aires'>Buenos Aires</option>
								<option value='Catamarca'>Catamarca</option>
								<option value='Chaco'>Chaco</option>
								<option value='Chubut'>Chubut</option>
								<option value='Ciudad de Buenos Aires'>Ciudad de Buenos Aires</option>
								<option value='Cordoba'>C&oacute;rdoba</option>
								<option value='Corrientes'>Corrientes</option>
								<option value='Entre R&iacute;os'>Entre R&iacute;os</option>
								<option value='Formosa'>Formosa</option>
								<option value='Jujuy'>Jujuy</option>
								<option value='La Pampa'>La Pampa</option>
								<option value='La Rioja'>La Rioja</option>
								<option value='Mendoza'>Mendoza</option>
								<option value='Misiones'>Misiones</option>
								<option value='Neuqu&eacute;n'>Neuqu&eacute;n</option>
								<option value='Rio Negro'>R&iacute;o Negro</option>
								<option value='Salta'>Salta</option>
								<option value='San Juan'>San Juan</option>
								<option value='San Luis'>San Luis</option>
								<option value='Santa Cruz'>Santa Cruz</option>
								<option value='Santa Fe'>Santa Fe</option>
								<option value='Santiago del Estero'>Santiago del Estero</option>
								<option value='Tierra del Fuego, Ant&aacute;rtida e Islas del Atl&aacute;ntico Sur'>Tierra del Fuego, Ant&aacute;rtida e Islas del Atl&aacute;ntico Sur</option>
								<option value='Tucuman'>Tucum&aacute;n</option>
                            </select></dd>
                        <dt><label for="mail">Localidad:</label></dt>
                        <dd><input type="text" id="localidad" name="localidad"><br></dd>
                        
                    	<span class="titulo" style="color: black;"><strong>Alojamiento</strong></span>
                    	<dt><label for="alojamiento">Cantidad de personas que asisten:</label></dt>
                        <dd>
                        	<select name="alojamiento" id="alojamiento">
                            	<option value="1">1 (Una)</option>
                                <option value="2">2 (Dos)</option>
                                <option value="3">3 (Tres)</option>
                                <option value="4">4 (Cuatro)</option>
                                <option value="5">5 (Cinco)</option>
                                <option value="5">6 (Seis)</option>
                                <option value="5">7 (Siete)</option>
                                <option value="5">8 (Ocho)</option>
                                <option value="5">9 (Nueve)</option>
                                <option value="5">10 (Diez)</option>
                                <option value="5">11 (Once)</option>
                                <option value="5">12 (Doce)</option>
                                <option value="5">13 (Trece)</option>
                            </select>
                        </dd>
                        <dt><label for="asistencia">Si son mas de una las personas que asisten, por favor complete los nombre y apellido uno debajo del otro:</label></dt>
                        <dd><textarea name="asistencia" id="asistencia"></textarea></dd>
                        <dt><label for="entradas">Cuantas de las personas que asisten son concursantes?:</label></dt>
                        <dd>
                        	<select name="concursantes" id="concursantes">
                            	<option value="1">1 (Una)</option>
                                <option value="2">2 (Dos)</option>
                                <option value="3">3 (Tres)</option>
                                <option value="4">4 (Cuatro)</option>
                                <option value="5">5 (Cinco)</option>
                                <option value="5">6 (Seis)</option>
                                <option value="5">7 (Siete)</option>
                                <option value="5">8 (Ocho)</option>
                                <option value="5">9 (Nueve)</option>
                                <option value="5">10 (Diez)</option>
                                <option value="5">11 (Once)</option>
                                <option value="5">12 (Doce)</option>
                                <option value="5">13 (Trece)</option>
                            </select>
                        </dd>

                        <dt><label for="entradas">Cantidad de lugares para alojarses:<br>(cantidad de casas/deptos/hab. de hotel, etc)</label></dt>
                        <dd>
                        	<select name="entradas" id="entradas">
                            	<option value="1">1 (Una)</option>
                                <option value="2">2 (Dos)</option>
                                <option value="3">3 (Tres)</option>
                                <option value="4">4 (Cuatro)</option>
                                <option value="5">5 (Cinco)</option>
                            </select>
                        </dd>
                        
                        <span class="titulo" style="color: black;"><strong>Participaci&oacute;n en actividades</strong></span>
                        <dt><label for="deForm"><input type="checkbox" value="1" checked="true" name="excursiones" id="excursiones" />&nbsp;Deseo informaci&oacute;n para las excursiones, quiero participar</label><br><br></dt>
                        <dt><label for="deForm"><input type="checkbox" value="1" checked="true" name="cena" id="cena" />&nbsp;Deseo reservar entradas para la cena, quiero participar</label><br><br></dt>
                    	<dt><label for="comentario">Comentario:</label></dt>
                        <dd><textarea name="comentario" id="comentario"></textarea></dd>
                     </dl>
                    Cualquier inconveniente escribinos a <a style="text-decoration: underline;color:blue;" href="mailto:tejo@balneario-el-condor.com.ar">Tejo El Condor</a><a class="botonEnviar" id="enviarFormulario" href="#">Enviar inscripci&oacute;n</a>

                </form>
            </div>
        </section>
        <!-- /fullCol -->
      </div>
    </section>
    <script type="text/javascript">
    $(document).ready(function(){

        $('#enviarFormulario').click(function(){
            var nombre      = $("#nombre").val();
            var apellido    = $("#apellido").val();
            var telefono    = $("#telefono").val();
            var mail        = $("#mail").val();
            var nombreclub  = $("#nombreclub").val();
 
            if (nombre != "" && nombreclub != "" && apellido != "" && telefono != "" && mail != ""){
            	$.post( "/landing/anotarse",$("#AltaFormulario").serialize() )
            	  .done(function( data ) {
            	    alert(data );
            	  });
            }else{
                alert('Debe completar todos los campos con (*)');
            }
        });


           
    });
    </script>