<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Suscripci&oacute;n Ubbimaps</title>
</head>

<body>
<table width="596" border="0" cellspacing="0" cellpadding="0" style="margin:20px auto;">
  <tr>
    <td rowspan="3"><img src="http://ubbimap.com/img/mail/img1.jpg" width="192" height="209"/></td>
    <td><img src="http://ubbimap.com/img/mail/img2.jpg" width="405" height="90"/></td>
  </tr>
  <tr style="background-color:#ececec;">
  <td style="padding:0px 10px;"><p style="font-family:Arial, Helvetica, sans-serif; color:#5788ad;font-weight:bold;">Bienvenido a Ubbimap</p></td>
  </tr>
  <tr style="background-color:#ececec;">
 <td style="padding:0px 10px;"><p style="font-family:Arial, Helvetica, sans-serif;font-size:11px;">
 	Te acercamos tu usuario y clave para que puedas utilizar nuestro servicio<br />
 	<strong>usuario:</strong> <?php echo $this->usuario; ?><br />
 	<strong>clave:</strong> <?php echo $this->clave; ?><br />
 </p></td>
</table>

</body>
</html>