<!--==============================content=================================-->
<meta property="og:description" content="Encontre este clasificado en la web del Balneario, hace click y mira toda la descripción" />
<link href="/css/sorting.css" rel="stylesheet" />
     <link href="/css/animation.css" rel="stylesheet" />
<link href="/jackbox/css/jackbox.css" rel="stylesheet" type="text/css" />
  <link href="/jackbox/css/jackbox_hovers.css" rel="stylesheet" type="text/css" />

<div id="content">   
  <div class="row-title">
    <div class="container">
      <h2><?php echo $this->alquiler[0]["uim_titulo"]; ?></h2>
      <div class="breadcrumb"> <span><a href="/">Inicio</a></span> 
      <i class="fa fa-angle-right"></i><span><a href="/alquiler">Alquileres</a></span>
      <i class="fa fa-angle-right"></i><?php echo $this->alquiler[0]["uim_titulo"]; ?></div>
    </div>
  </div>
  <div class="container">
    <!--/*
  *
  * Revive Adserver Asynchronous JS Tag
  * - Generated with Revive Adserver v3.2.1
  *
  */-->

<ins data-revive-zoneid="3" data-revive-id="86d30993f9fb0ee5ee68abe6fb1d5366"></ins>
<script async src="//adserver.fidegroup.com.ar/www/delivery/asyncjs.php"></script>
    <div class="row content-div">
        <section class="span9 ss_p_right">
          <div class="clearfix t_xs_align_c">
          <div class="photoframe type_2 shadow r_corners fleft f_sm_none d_xs_inline_b product_single_preview relative m_right_30 m_bottom_5 m_sm_bottom_20 m_xs_right_0 w_mxs_full">
            <div class="relative d_inline_b m_bottom_10 qv_preview d_xs_block">
            
              <img id="zoom_image" src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
              	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
              	echo  ($this->alquiler[0]["uim_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
              	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
              	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
              	echo  ($this->alquiler[0]["uim_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>&w=450&h=450&zc=1" class="tr_all_hover" alt="">
              
            </div>
            <!--carousel-->
            <div class="relative qv_carousel_wrap">
              <button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_prev">
                <i class="fa fa-angle-left "></i>
              </button>
              <div class="qv_carousel_single d_inline_middle">
                <a class="jackbox" href="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>" 
                	data-group="images" 
                	data-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
                	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["fotos_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>">
                	<img src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen0"] != "")?$this->alquiler[0]["uim_imagen0"]:"no_image.jpg";?>&w=110&h=110&zc=1" alt="">
                </a>
                
                <a class="jackbox" href="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen1"] != "")?$this->alquiler[0]["uim_imagen1"]:"no_image.jpg";?>" 
                	data-group="images" 
                	data-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen1"] != "")?$this->alquiler[0]["uim_imagen1"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
                	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["fotos_imagen0"] != "")?$this->alquiler[0]["uim_imagen1"]:"no_image.jpg";?>">
                	<img src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen1"] != "")?$this->alquiler[0]["uim_imagen1"]:"no_image.jpg";?>&w=110&h=110&zc=1" alt="">
                </a>
                
                <a class="jackbox" href="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen2"] != "")?$this->alquiler[0]["uim_imagen2"]:"no_image.jpg";?>" 
                	data-group="images" 
                	data-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen2"] != "")?$this->alquiler[0]["uim_imagen2"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
                	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["fotos_imagen0"] != "")?$this->alquiler[0]["uim_imagen2"]:"no_image.jpg";?>">
                	<img src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen2"] != "")?$this->alquiler[0]["uim_imagen2"]:"no_image.jpg";?>&w=110&h=110&zc=1" alt="">
                </a>
                
                <a class="jackbox" href="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen3"] != "")?$this->alquiler[0]["uim_imagen3"]:"no_image.jpg";?>" 
                	data-group="images" 
                	data-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen3"] != "")?$this->alquiler[0]["uim_imagen3"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
                	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["fotos_imagen0"] != "")?$this->alquiler[0]["uim_imagen3"]:"no_image.jpg";?>">
                	<img src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen3"] != "")?$this->alquiler[0]["uim_imagen3"]:"no_image.jpg";?>&w=110&h=110&zc=1" alt="">
                </a>
                
                <a class="jackbox" href="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen4"] != "")?$this->alquiler[0]["uim_imagen4"]:"no_image.jpg";?>" 
                	data-group="images" 
                	data-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen4"] != "")?$this->alquiler[0]["uim_imagen4"]:"no_image.jpg";?>&w=450&h=450&zc=1" 
                	data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["fotos_imagen0"] != "")?$this->alquiler[0]["uim_imagen4"]:"no_image.jpg";?>">
                	<img src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://<?php 
                	echo $_SERVER["SERVER_NAME"]; ?>/imagenes/alquiler/<?php 
                	echo  ($this->alquiler[0]["uim_imagen4"] != "")?$this->alquiler[0]["uim_imagen4"]:"no_image.jpg";?>&w=110&h=110&zc=1" alt="">
                </a>
              </div>
              <button class="button_type_11 bg_light_color_1 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_single_next">
                <i class="fa fa-angle-right "></i>
              </button>
            </div>
          </div>
          <div class="v_space3 t_xs_align_l shop_section">
            <!--description-->
            <h2 class="m_bottom_15 txt_trans"><?php echo $this->alquiler[0]["uim_titulo"]; ?></h2>
            <div class="m_bottom_15">
              <span class="txt-1 v_reviews">  
                Telefono: <?php echo $this->alquiler[0]["uim_telefono"]; ?>
              </span>
            </div>
            <div class="m_bottom_15">
              <span class="txt-1 v_reviews">  
                Direccion: <?php echo $this->alquiler[0]["uim_direccion"]; ?>
              </span>
            </div>
            <div class="m_bottom_15">
              <span class="txt-1 v_reviews">  
                E-Mail: <?php echo $this->alquiler[0]["uim_mail"]; ?>
              </span>
            </div>
            <div class="m_bottom_15">
              <span class="txt-1 v_reviews">  
                Contacto: <?php echo $this->alquiler[0]["uim_contacto"]; ?>
              </span>
            </div>
            <div class="m_bottom_15">
              <span class="txt-1 v_reviews">  
                Descripcion: <?php echo $this->alquiler[0]["uim_descripcion"]; ?>
              </span>
            </div>
            <hr class="m_bottom_15 m_t_no_space">


          </div>
        </div>
        
     
      </section>
      
    </div>         
  </div>    
</div>
    <script src="/js/elevatezoom.min.js"></script>
  <script src="/js/owl.carousel.min.js"></script>
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/es_LA/all.js"></script>


<script src="/js/jquery.isotope.js"></script>
  <script>
    jQuery(window).load(function() {  
    var jQuerycontainer = jQuery('.projects');
    //Run to initialise column sizes
    //updateSize();

    //Load masonry when images all loaded
    jQuerycontainer.imagesLoaded( function(){

        jQuerycontainer.isotope({
            // options
            itemSelector : '.element',  
            layoutMode : 'masonry',
            transformsEnabled: false,
            columnWidth: function( containerWidth ) {
                containerWidth = jQuerybrowserWidth;
                return Math.floor(containerWidth / jQuerycols);
              }
        });
    });
    
      // update columnWidth on window resize
    jQuery(window).smartresize(function(){  
        updateSize();
        jQuerycontainer.isotope( 'reLayout' );
    });

  
    //Set item size
    function updateSize() {
        jQuerybrowserWidth = jQuerycontainer.width();
        jQuerycols = 4;

        if (jQuerybrowserWidth >= 1200) {
            jQuerycols = 4;
        }
        else if (jQuerybrowserWidth >= 980 && jQuerybrowserWidth < 1200) {
            jQuerycols = 4;
        }
    
       else if (jQuerybrowserWidth >= 768 && jQuerybrowserWidth < 979) {
            jQuerycols = 4;
        }
    
    
        else if (jQuerybrowserWidth >= 401 && jQuerybrowserWidth < 767) {
            jQuerycols = 2;
        }
        else if (jQuerybrowserWidth < 400) {
            jQuerycols = 2;
        }

        //console.log("Browser width is:" + jQuerybrowserWidth);
        //console.log("Cols is:" + jQuerycols);

        // jQuerygutterTotal = jQuerycols * 20;
    jQuerybrowserWidth = jQuerybrowserWidth; // - jQuerygutterTotal;
        jQueryitemWidth = jQuerybrowserWidth / jQuerycols;
        jQueryitemWidth = Math.floor(jQueryitemWidth);

        jQuery(".element").each(function(index){
            jQuery(this).css({"width":jQueryitemWidth+"px"});             
        });
      
    
  var jQueryoptionSets = jQuery('#options .option-set'),
    jQueryoptionLinks = jQueryoptionSets.find('a');

  jQueryoptionLinks.click(function(){
  var jQuerythis = jQuery(this);
  // don't proceed if already selected
  if ( jQuerythis.hasClass('selected') ) {
    return false;
  }
  var jQueryoptionSet = jQuerythis.parents('.option-set');
  jQueryoptionSet.find('.selected').removeClass('selected');
  jQuerythis.addClass('selected');

  // make option object dynamically, i.e. { filter: '.my-filter-class' }
  var options = {},
    key = jQueryoptionSet.attr('data-option-key'),
    value = jQuerythis.attr('data-option-value');
  // parse 'false' as false boolean
  value = value === 'false' ? false : value;
  options[ key ] = value;
  if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
    // changes in layout modes need extra logic
    changeLayoutMode( jQuerythis, options )
  } else {
    // otherwise, apply new options
    jQuerycontainer.isotope( options );
  }
  
  return false;
  });   
    
    };      
    
    });
  </script>
    <script type="text/javascript" src="/jackbox/js/libs/Jacked.js"></script>
    <script type="text/javascript" src="/jackbox/js/jackbox-swipe.js"></script>
    <script type="text/javascript" src="/jackbox/js/jackbox.js"></script>
    <script type="text/javascript" src="/jackbox/js/libs/StackBlur.js"></script>
    <script>
      $(document).ready(function() {    
  jQuery(".jackbox[data-group]").jackBox("init",{deepLinking: true});
      })
    </script>
   
<script>
    FB.init({
        appId  : "341020419335849",
        status : true,
        cookie : true,
        xfbml  : true
    });
 function postToFeed(linkEnviado,pictureEnviada,tituloEnviado,descripcionEnviado) {

        // calling the API ...
        var obj = {
          method: 'feed',
          redirect_uri: 'http://www.balneario-el-condor.com.ar',
          link: linkEnviado,
          picture: pictureEnviada,
          name: tituloEnviado,
          caption: '',
          description: descripcionEnviado
        };

        function callback(response) {
        }

        FB.ui(obj, callback);
      }

       !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id)){
          js=d.createElement(s);
          js.id=id;
          js.src="https://platform.twitter.com/widgets.js";

          fjs.parentNode.insertBefore(js,fjs);
        }
      }
          (document,"script","twitter-wjs");
</script>