<section class="page-header page-header-modern bg-color-primary page-header-md ">
  <div class="container-fluid">
    <div class="row align-items-center">

      <div class="col">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <div class="overflow-hidden pb-2">
              <h1 class="text-light font-weight-bold text-9 appear-animation animated maskUp appear-animation-visible" data-appear-animation="maskUp" data-appear-animation-delay="100" style="animation-delay: 100ms;"><?php echo 'Colectivos al Condor' ?></h1>
            </div>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-md-center appear-animation animated fadeIn appear-animation-visible" data-appear-animation="fadeIn" data-appear-animation-delay="300" style="animation-delay: 300ms;">
              <li><a class="font-weight-semibold" href="/" style="color: #e2a522;font-size: 16px;">Inicio</a></span></li>
              <li></span> <i class="fa fa-angle-right"></i><span class="active" style="color: #e2a522;font-size: 16px;"> <?php echo 'Horarios de Colectivo' ?></span></a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<!--==============================content=================================-->

<div class="container pt-3 pb-2">

  <div class="row portfolio-list sort-destination">
    <div class="col">
      <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Mapa de Recorrido</strong></h2>
      <br>
       </div>
      <p class="lead" style="text-align: justify">&Uacute;ltima Actualizaci&oacute;n: 17/12/2017</p>
      <iframe src="https://mapsengine.google.com/map/embed?mid=zWFXHptoQFKU.kkQreHaBxjrE" width="400" height="613"></iframe>
      <br>
      <blockquote class="with-borders" style="text-align: justify">
                    <p><h4>El costo del pasaje es de 35 pesos.</h4><br>
      Paradas oficiales en los tramos de inicio y finalizaci&oacute;n, tambi&eacute;n es posible (dependiendo de la capacidad del colectivo) tomarlo en las diferentes paradas del colectivo local.</p>
                    <footer><h4>Tel&eacute;fono de la empresa (Ceferino):(02920) 424542</h4></footer>
                  </blockquote>
    </div>
      <div id="examples" class="container py-2">
    <div class="row">
      <div class="col-lg-12">
       <div class="divider divider-primary">
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>
  <div class="row portfolio-list sort-destination">
      <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Horarios</strong></h2>
    </div>
    <div>
      <table class="table table-bordered">
        <tbody><tr>
          <td>
            <div>
              <table class="table table-bordered">
                <tbody>
                  <tr style="color:#A61B4A;background-color: #e8e8e8 !important;">
                    <td  style="width: 210px;">
                      <b style="color:#A61B4A;">D&iacute;as</b>
                    </td>
                    <td>
                      <b style="color:#A61B4A;">Sale de Viedma</b>
                    </td>
                    <td>
                      <b style="color:#A61B4A;">Llega al C&oacute;ndor</b>
                    </td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as</td>
                    <td>07:00 hs.</td>
                    <td>07:40 hs.</td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as</td>
                    <td>09:00 hs.</td>
                    <td>09:40 hs.</td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as</td>
                    <td>11:00 hs.</td>
                    <td>11:40 hs.</td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as&nbsp;<b>*</b></td>
                    <td>14:00 hs.</td>
                    <td>14:40 hs.</td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as</td>
                    <td>18:00 hs.</td>
                    <td>18:40 hs.</td>
                  </tr>
                  <tr>
                    <td>Todos los d&iacute;as</td>
                    <td>21:00 hs.</td>
                    <td>21:40 hs.</td>
                  </tr>
                </tbody></table>
              </div>
              <div>
                <table class="table table-bordered">
                  <tbody>
                    <tr style="color:#3F5BA9;background-color: #e8e8e8 !important;">
                      <td style="width: 210px;">
                        <b style="color:#3F5BA9;">D&iacute;as</b>
                      </td>
                      <td>
                        <b style="color:#3F5BA9;">Sale del C&oacute;ndor</b>
                      </td>
                      <td>
                        <b style="color:#3F5BA9;">Llega a Viedma</b>
                      </td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>08:00 hs.</td>
                      <td>08:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>10:00 hs.</td>
                      <td>10:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>12:00 hs.</td>
                      <td>12:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>15:00 hs.</td>
                      <td>15:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>19:00 hs.</td>
                      <td>19:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>20:30 hs.</td>
                      <td>21:10 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>22:00 hs.</td>
                      <td>22:40 hs.</td>
                    </tr>
                  </tbody></table>
                </div>
                <div>
                  <table class="table table-bordered">
                    <tbody>
                      <tr style="color:#3F5BA9;background-color: #e8e8e8 !important;">
                        <td  style="width: 210px;">
                          <b style="color:#3F5BA9;">D&iacute;as</b>
                        </td>
                        <td>
                          <b style="color:#3F5BA9;">Sale de Viedma</b>
                        </td>
                        <td>
                          <b style="color:#3F5BA9;">Llega a Lober&iacute;a</b>
                        </td>
                      </tr>
                      <tr>
                        <td>S&aacute;bados, Domingos y Feriados</td>
                        <td>09:00 hs.</td>
                        <td>10:40 hs.</td>
                      </tr>
                      <tr>
                        <td>Todos los d&iacute;as</td>
                        <td>14:00 hs.</td>
                        <td>15:40 hs.</td>
                      </tr>
                    </tbody></table>
                  </div>
                  <div>
                    <table class="table table-bordered">
                      <tbody>
                        <tr style="color:#3F5BA9;background-color: #e8e8e8 !important;">
                          <td style="width: 210px;">
                            <b style="color:#3F5BA9;">D&iacute;as</b>
                          </td>
                          <td>
                            <b style="color:#3F5BA9;">Sale de Lober&iacute;a</b>
                          </td>
                          <td>
                            <b style="color:#3F5BA9;">Llega a Viedma</b>
                          </td>
                        </tr>
                        <tr>
                          <td>Todos los d&iacute;as</td>
                          <td>20:00 hs.</td>
                          <td>21:10 hs.</td>
                        </tr>
                      </tbody></table>
                    </div>
                  </td>
                </tr>
              </tbody></table>
            </div>
          </div>


        
        </div><!-- row -->



  </div>

   <script>
      $( document ).ready(function() {
        $('.dropdown-item').removeClass("active");
        $('#interes').addClass("active");
      });

    </script>
    


  
