<section class="page-header page-header-modern bg-color-primary page-header-md ">
  <div class="container-fluid">
    <div class="row align-items-center">

      <div class="col">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <div class="overflow-hidden pb-2">
              <h1 class="text-light font-weight-bold text-9 appear-animation animated maskUp appear-animation-visible" data-appear-animation="maskUp" data-appear-animation-delay="100" style="animation-delay: 100ms;"><?php echo 'Ubicación' ?></h1>
            </div>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-md-center appear-animation animated fadeIn appear-animation-visible" data-appear-animation="fadeIn" data-appear-animation-delay="300" style="animation-delay: 300ms;">
              <li><a class="font-weight-semibold" href="/" style="color: #e2a522;font-size: 16px;">Inicio</a></span></li>
              <li></span> <i class="fa fa-angle-right"></i><span class="active " style="color: #e2a522;font-size: 16px;"> <?php echo 'Ubicación' ?></span></a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<!--==============================content=================================-->

<div class="container pt-3 pb-2">

  <div class="row pt-2">
    <div class="col">
      <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Villa Mar&iacute;tima El Condor</strong></h2>
      <p class="lead" style="text-align: justify">
        <br>
A 30 kil&oacute;metros de Viedma, donde se unen el r&iacute;o Negro y el mar, se encuentra el balneario El C&oacute;ndor, Portal de Ingreso a la Patagonia Atl&aacute;ntica. Caracterizado por la extensi&oacute;n de sus playas y la presencia de la Colonia de loros mas grande del mundo.<br><br>
<strong>Atractivos Hist&oacute;ricos y Religiosos:</strong><br>
Mirador Ceferino Namuncur&aacute;: en el nacimiento del acantilado, la familia P&eacute;rez, erigi&oacute; una
estatua como ofrenda a Ceferino Namuncur&aacute;, con una enorme cruz y una ermita. La ofrenda se
realiz&oacute; en cumplimiento de una promesa a cambio de salud y lluvia, ya que una gran sequ&iacute;a
estaba afectando a la regi&oacute;n. Hoy constituye un punto panor&aacute;mico desde donde se puede
observar la belleza de la villa y la desembocadura del r&iacute;o en el mar.<br><br>
Faro del R&iacute;o Negro: Fue inaugurado el 25 de mayo de 1887 por el General Lorenzo Winter con
el objeto de ser un punto de referencia para los barcos que se acercan a esta zona de la costa.
Fue el primer faro continental de la Patagonia, y actualmente es la se&ntilde;al m&aacute;s antigua en
servicio con personal de custodia. Su altura sobre el nivel del mar es de 45.62 metros, y se&ntilde;ala
el comienzo de los acantilados de la costa Patag&oacute;nica.<br><br>
Iglesia "Stella Maris": Las primeras misas del balneario se celebraban en las casas de algunos
vecinos de El C&oacute;ndor, quienes a&ntilde;os mas tarde lograron con gran esfuerzo, la construcci&oacute;n de
la capilla, que fue bendecida bajo el nombre de Stella Maris el 23 de enero de 1960.
            </p>
    </div>
  </div>
  
  <div id="examples" class="container py-2">
    <div class="row">
      <div class="col-lg-12">
       <div class="divider divider-primary">
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>
<div class="row pt-2">
  <div class="col">
    <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Ubicación</strong></h2>
  </div>
  <div id="map_canvas" class="google-map mt-0 mb-0" style="height: 400px; position: relative; overflow: hidden;"><div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; background-color: rgb(229, 227, 223);"><div class="gm-err-container"><div class="gm-err-content"><div class="gm-err-icon"><img src="https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png" draggable="false" style="user-select: none;"></div><div class="gm-err-title">Se produjo un error.</div><div class="gm-err-message">Esta página no cargó bien Google Maps. Consulta la consola de JavaScript para obtener los detalles técnicos.</div></div></div></div></div>
</div>
</div>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<?php
$coordenadas = explode(",",str_replace(")","",str_replace("(", "", $this->cercanos[0]["ce_googlemaps"])));
?>
<script type="text/javascript">
    var initialLocation;
    var browserSupportFlag =  new Boolean();
    var map;
    var infowindow = new google.maps.InfoWindow();
    var latitud  = '-41.043258';
    var longitud = '-62.826731';
    var myOptions = {
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.SATELLITE
        };
        map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      

        initialLocation = new google.maps.LatLng(latitud,longitud);
        contentString = "<?php echo $this->cercanos[0]["ce_titulo"]; ?>";
        map.setCenter(initialLocation);
        infowindow.setContent(contentString);
        infowindow.setPosition(initialLocation);
        infowindow.open(map);
</script>