<section class="page-header page-header-modern bg-color-primary page-header-md ">
  <div class="container-fluid">
    <div class="row align-items-center">

      <div class="col">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <div class="overflow-hidden pb-2">
              <h1 class="text-light font-weight-bold text-9 appear-animation animated maskUp appear-animation-visible" data-appear-animation="maskUp" data-appear-animation-delay="100" style="animation-delay: 100ms;"><?php echo $this->Hospedaje[0]["ho_titulo"]; ?></h1>
            </div>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-md-center appear-animation animated fadeIn appear-animation-visible" data-appear-animation="fadeIn" data-appear-animation-delay="300" style="animation-delay: 300ms;">
              <li><a class="font-weight-semibold" href="/" style="color: #e2a522;font-size: 16px;">Inicio</a></span></li>
              <li><a class="active font-weight-semibold" href="/hospedaje" style="color: #e2a522;font-size: 16px;">Hospedaje</a></span> <i class="fa fa-angle-right"></i><span class="active " style="color: #e2a522;font-size: 16px;"> <?php echo $this->Hospedaje[0]["ho_titulo"]; ?></span></a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<!--==============================content=================================-->

<div class="container pt-3 pb-2">

  <div class="row pt-2">
    <div class="col">
      <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Descripción</strong></h2>
      <br>
      <p class="lead" style="text-align: justify"><?php echo utf8_encode($this->Hospedaje[0]["ho_descripcion"]); ?></p>
    </div>
  </div>
  <div id="examples" class="container py-2">
    <div class="row">
      <div class="col-lg-12">
       <div class="divider divider-primary">
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>
<div class="row pt-2">
  <div class="col">
    <h2 class="font-weight-normal text-7 mb-2"><strong class="font-weight-extra-bold">Ubicación</strong></h2>
  </div>
  <div id="map_canvas" class="google-map mt-0 mb-0" style="height: 400px; position: relative; overflow: hidden;"><div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; background-color: rgb(229, 227, 223);"><div class="gm-err-container"><div class="gm-err-content"><div class="gm-err-icon"><img src="https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png" draggable="false" style="user-select: none;"></div><div class="gm-err-title">Se produjo un error.</div><div class="gm-err-message">Esta página no cargó bien Google Maps. Consulta la consola de JavaScript para obtener los detalles técnicos.</div></div></div></div></div>
</div>
</div>
</div>








<!--==========end carousel-3=============-->  
<!--==========carousel-3=============--
      <div class="row-recent extra v_space m_sm_bottom_20">
        <h3>Imagenes</h3>
         
        <div class="carousel-3  carousel">
          <ul id="carousel-3_3" class="clearfix"> 
            <li>
              <figure class="img-polaroid view view-sixth">
                <img src="/img/index-img_19.jpg" alt="">
                <div class="mask">
                  <div> 
                    <span><a href="#">Mauris Fermentum</a></span>
                    <strong><a href="#">Projects</a></strong>
                  </div>                     
                </div>
              </figure>
            </li>
            <li>
              <figure class="img-polaroid view view-sixth">
                <img src="/img/index-img_3.jpg" alt="">
                <div class="mask">
                  <div> 
                    <span><a href="#">Mauris Fermentum</a></span>
                    <strong><a href="#">Projects</a></strong>
                  </div>                     
                </div>
              </figure>
            </li>
            <li>
              <figure class="img-polaroid view view-sixth">
                <img src="/img/index-img_4.jpg" alt="">
                <div class="mask">
                  <div> 
                    <span><a href="#">Mauris Fermentum</a></span>
                    <strong><a href="#">Projects</a></strong>
                  </div>                     
                </div>
              </figure>
            </li>
            <li>
              <figure class="img-polaroid view view-sixth">
                <img src="/img/index-img_5.jpg" alt="">
                <div class="mask">
                  <div> 
                    <span><a href="#">Mauris Fermentum</a></span>
                    <strong><a href="#">Projects</a></strong>
                  </div>                     
                </div>
              </figure>
            </li>
    
          </ul>
              <div class="div-control"> <div  class="prev-slide prev-2"></div> <div class="next-slide next-2"></div> </div>
            </div>
           
    
          </div> !--==========end carousel-3=============-->
          
        </div>
        
      </div>
    </div>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <?php
    $coordenadas = explode(",",str_replace(")","",str_replace("(", "", $this->Hospedaje[0]["ho_googlemaps"])));
    ?>
    <script type="text/javascript">
      var initialLocation;
      var browserSupportFlag =  new Boolean();
      var map;
      var infowindow = new google.maps.InfoWindow();
      var latitud  = '<?php echo $coordenadas[0]; ?>';
      var longitud = '<?php echo $coordenadas[1]; ?>';
      var myOptions = {
        zoom: 17,
        mapTypeId: google.maps.MapTypeId.SATELLITE
      };
      map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      

      initialLocation = new google.maps.LatLng(latitud,longitud);
      contentString = "<?php echo $this->Hospedaje[0]["ho_titulo"]; ?>";
      map.setCenter(initialLocation);
      infowindow.setContent(contentString);
      infowindow.setPosition(initialLocation);
      infowindow.open(map);
    </script>