<div id="content">   
  <div class="row-title">
    <div class="container">
      <h2>Puntos limpios</h2>
      
      <div class="breadcrumb"> <span><a href="/">Inicio</a></span> <i class="fa fa-angle-right"></i><span>Puntos limpios</div>
    </div>
  </div>
  <div class="container">
    <div class="row content-div v_contact_form2 v_contact_form m_sm_bottom_20">
      <article class="span7">
        <h3>Puntos Limpios</h3>
        <h7>&Uacute;ltima Actualizaci&oacute;n: 31/10/2019</h7> 
        <iframe src="https://mapsengine.google.com/map/embed?mid=zWFXHptoQFKU.kkQreHaBxjrE" width="640" height="613"></iframe>
      </article>
      <article class="span5">
          <h3>Puntos Limpios</h3>  
          <table class="tab_var1">
            <tbody><tr>
              <td class="tab_var1_pad">
                <div class="v_tables">
                  <table>
                    <tbody>
                    <tr style="color:#A61B4A">
                      <td  style="width: 210px;">
                        <b style="color:#A61B4A;">D&iacute;as</b>
                      </td>
                        <td>
                          <b style="color:#A61B4A;">Sale de Viedma</b>
                        </td>
                        <td>
                          <b style="color:#A61B4A;">Llega al C&oacute;ndor</b>
                        </td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>07:00 hs.</td>
                      <td>07:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>09:00 hs.</td>
                      <td>09:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>11:00 hs.</td>
                      <td>11:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as&nbsp;<b>*</b></td>
                      <td>14:00 hs.</td>
                      <td>14:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>18:00 hs.</td>
                      <td>18:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>21:00 hs.</td>
                      <td>21:40 hs.</td>
                    </tr>
                  </tbody></table>
                </div>
                <div class="v_tables">
                  <table>
                    <tbody>
                    <tr style="color:#3F5BA9">
                      <td style="width: 210px;">
                        <b style="color:#3F5BA9;">D&iacute;as</b>
                      </td>
                        <td>
                          <b style="color:#3F5BA9;">Sale del C&oacute;ndor</b>
                        </td>
                        <td>
                          <b style="color:#3F5BA9;">Llega a Viedma</b>
                        </td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>08:00 hs.</td>
                      <td>08:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>10:00 hs.</td>
                      <td>10:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>12:00 hs.</td>
                      <td>12:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>15:00 hs.</td>
                      <td>15:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>19:00 hs.</td>
                      <td>19:40 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>20:30 hs.</td>
                      <td>21:10 hs.</td>
                    </tr>
                                        <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>22:00 hs.</td>
                      <td>22:40 hs.</td>
                    </tr>
                  </tbody></table>
                </div>
                <div class="v_tables">
                  <table>
                    <tbody>
                    <tr style="color:#3F5BA9">
                      <td  style="width: 210px;">
                        <b style="color:#3F5BA9;">D&iacute;as</b>
                      </td>
                        <td>
                          <b style="color:#3F5BA9;">Sale de Viedma</b>
                        </td>
                        <td>
                          <b style="color:#3F5BA9;">Llega a Lober&iacute;a</b>
                        </td>
                    </tr>
                    <tr>
                      <td>S&aacute;bados, Domingos y Feriados</td>
                      <td>09:00 hs.</td>
                      <td>10:40 hs.</td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>14:00 hs.</td>
                      <td>15:40 hs.</td>
                    </tr>
                  </tbody></table>
                </div>
                <div class="v_tables">
                  <table>
                    <tbody>
                    <tr style="color:#3F5BA9">
                      <td style="width: 210px;">
                        <b style="color:#3F5BA9;">D&iacute;as</b>
                      </td>
                        <td>
                          <b style="color:#3F5BA9;">Sale de Lober&iacute;a</b>
                        </td>
                        <td>
                          <b style="color:#3F5BA9;">Llega a Viedma</b>
                        </td>
                    </tr>
                    <tr>
                      <td>Todos los d&iacute;as</td>
                      <td>20:00 hs.</td>
                      <td>21:10 hs.</td>
                    </tr>
                  </tbody></table>
                </div>
              </td>
            </tr>
          </tbody></table>
      </article>
    </div>         
  </div>    
</div>


