        <!-- Main Container -->
            <main id="main-container">
                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-8">
                            <h1 class="page-heading">
                                Novedad <small>Formulario de <?php echo (isset($this->arrNovedades[0]["nov_id"]))?"edici&oacute;n":"alta"; ?> para un novedad.</small>
                            </h1>
                        </div>
                        <div class="col-sm-4 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li><a class="link-effect" href="/evento/listado">Novedad</a></li>
                                <li><?php echo (isset($this->arrNovedades[0]["nov_id"]))?"Edici&oacute;n":"Alta"; ?></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->
                <?php  //print_r($this->arrNovedades);exit(); ?>
                <!-- Page Content -->
                <div class="content content-narrow">

				<!-- Bootstrap Design -->
                    <div class="row">
                            <!-- Default Elements -->
                            <div class="block">
                            	<div class="alert alert-success" id="mensajeOK" style="display:none;">
								  <strong>Perfecto!</strong> <?php echo (isset($this->arrNovedades[0]["nov_id"]))?"Edici&oacute;n":"Alta"; ?> de la novedad correcta. <a href="/novedades/listado">Ir al listado</a>
								</div>
								<div class="alert alert-danger" id="mensajeERROR" style="display:none;">
								  <strong>Upps!</strong> Existen errores, por favor verificalos.
								</div>
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button"><i class="si si-settings"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Formulario de <?php echo (isset($this->arrNovedades[0]["nov_id"]))?"Edici&oacute;n":"Alta"; ?></h3>
                                </div>
                                <div class="block-content block-content-narrow">
                                    <form class="form-horizontal" action="base_forms_elements.html" method="post" enctype="multipart/form-data" onsubmit="return false;">
                                        <input type="hidden" id="nov_id" name="nov_id" value="<?php echo $this->arrNovedades[0]["nov_id"]; ?>" />
                                        <div class="form-group">
                                            <label class="col-xs-12" for="example-text-input">Titulo</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" value='<?php echo utf8_encode($this->arrNovedades[0]["nov_titulo"]); ?>' type="text" id="titulo" name="titulo" placeholder="Titulo de la novedad">
                                                <!--  <div class="help-block">Nombre con el que luego</div> -->
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12" for="example-textarea-input">Descripci&oacute;n</label>
                                            <div class="col-xs-9">
                                                <textarea class="form-control" id="mensaje-confirmacion"  name="mensaje-confirmacion" rows="6" placeholder="Noticia, bla bla bla" ><?php echo utf8_encode($this->arrNovedades[0]["nov_descripcion"]); ?></textarea>     
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12" for="example-text-input">URL sufijo</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" value="<?php echo $this->arrNovedades[0]["nov_keyword"]; ?>" type="text" id="keyword" name="keyword" placeholder="nueva-novedad-a-colocar">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12" for="example-text-input">Link Video</label>
                                            <div class="col-sm-9">
                                                <input class="form-control" value="<?php echo $this->arrNovedades[0]["nov_video"]; ?>" type="text" id="nov_video" name="nov_video" placeholder="https://www.youtube.com/watch?v=yhO8DiNohyo">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-xs-12" for="example-text-input">Fecha de Publicaci&oacute;n</label>
                                            <div class="col-sm-9">
                                                <?php 
                                                $fechaHora = (isset($this->arrNovedades[0]["nov_fechahora"])?substr($this->arrNovedades[0]["nov_fechahora"],0,10):"");
                                                $arrFechaHora = ($fechaHora != "")?explode("-",$fechaHora):array(date("Y"),date("m"),date("d"));
                                                ?>
                                                <input class="js-datepicker form-control" value="<?php echo $arrFechaHora[2]."/".$arrFechaHora[1]."/".$arrFechaHora[0]; ?>" type="text" id="nov_fecha" name="nov_fecha" data-date-format="dd/mm/yyyy" placeholder="dd/mm/yyyy">
                                            </div>
                                        </div>
                                        <?php
                                        $ids = "";
                                        if (isset($this->arrImgenesArticulo)){
                                            foreach ($this->arrImgenesArticulo as $key => $value) {
                                                $ids .= ($ids != "")? ",".$value["img_id"]:$value["img_id"]; ?>
                                                <div id="<?php echo $value["img_id"]?>" class="col-sm-3" style="padding: 0px;margin-bottom: 20px;">
                                                <img src="/timthumb/timthumb.php?src=<?php echo $value["img_nombre"]; ?>&w=150&h=150&zc=1" />
                                                <button class="btn btn-xs btn-default" onclick='removerImagen("<?php echo $value["img_id"]?>")'; type="button" data-toggle="tooltip" title="Remover Imagen"><i class="fa fa-times"></i></button>
                                                </div>
                                        <?php }
                                        }
                                        ?>
                                        <div class="form-group" id="upload">
                                            <div class="col-sm-9">
                                            <label class="col-xs-12" for="example-text-input">Imagenes</label>
                                            <div id="fileuploader">Subir Archivo</div>
                                            <input type="hidden" value="<?php echo $ids; ?>" name="logo" id="logo"/>
                                        </div></div>
                                        <div class="form-group">
                                            <div class="col-xs-12">
                                                <button class="btn btn-sm btn-primary" type="submit">Guardar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- END Default Elements -->                        
                    </div>
                    </div>
                    </main>
                    <link href="https://rawgithub.com/hayageek/jquery-upload-file/master/css/uploadfile.css" rel="stylesheet">
                    <script src="https://rawgithub.com/hayageek/jquery-upload-file/master/js/jquery.uploadfile.min.js"></script>

                    <script>
                        jQuery(document).ready(function() {
                            $('.ajax-file-upload-error').html('');

                            $("#fileuploader").uploadFile({
                                url:"/novedades/upload",
                                fileName:"myfile",
                                maxFileCount:999,
                                multiple: true,
                                showDownload:false,
                                onSuccess:function(files,data,xhr,pd)
                                {   

                                    $('.ajax-file-upload-error').html('');
                                    /*if($('.ajax-file-upload-filename').size()==5){*/
                                    if($('.ajax-file-upload-error').css('display')!= 'none'){
                                        $('.ajax-file-upload-error').html('');
                                        $('.ajax-file-upload-error').html('No se puede subir mas de 999 archivos.');
                                        $('.ajax-file-upload-error').css('display', 'block');
                                    } 
                                    if(data!=''){
                                        if ($("#logo").val() != "") $("#logo").val($("#logo").val() + ',' + data); 
                                        else $("#logo").val(data); 
                                    }
                                    
                                }
                             
                            });
                        });

	                    jQuery( "form" ).on( "submit", function( event ) {
	                    	  event.preventDefault();
	                    	 jQuery( "#mensajeERROR" ).hide();
	                    	 jQuery( "#mensajeOK" ).hide();
	                    	 var datosAlta = $( this ).serialize();
                             var msjs= '&descripcion=' + CKEDITOR.instances['mensaje-confirmacion'].getData();
                             
	                    	 var jqxhr = $.ajax({url:"/novedades/save",data: datosAlta + msjs,method:"POST" } );
	                    	 jqxhr.done(function(data) {
	                    		 var obj = jQuery.parseJSON(data);
	                    		 console.log(obj);
	                    		 if (obj.proceso != "error"){
	                    		 	jQuery( "#mensajeOK" ).show();
	                    			var new_position = jQuery('.page-heading').offset();
	                    			window.scrollTo(new_position.left,new_position.top);
	                    		 }else{
	                    			jQuery( "#mensajeERROR" ).show();
		                    		var new_position = jQuery('.page-heading').offset();
		                    		window.scrollTo(new_position.left,new_position.top);
		                    	 }
	                    	  })
	                    	  jqxhr.fail(function() {
	                    		  jQuery( "#mensajeERROR" ).show();
	                    	  });
	                    	});
                            CKEDITOR.replace( 'mensaje-confirmacion' );   

                        function removerImagen(id_imagenArticulo){
                           $("#" + id_imagenArticulo).hide('slow');
                           $("#logo").val(
                                            $.grep($("#logo").val().split(','), function( n, i ) {
                                                  return n != id_imagenArticulo;
                                            }).join(',')
                                        );
                        }
                        
                    </script>
                    