<!--==============================content=================================-->
<meta property="og:description" content="Encontre este clasificado en la web del Balneario, hace click y mira toda la descripción" />
<link href="/css/sorting.css" rel="stylesheet" />
     <link href="/css/animation.css" rel="stylesheet" />
<link href="/jackbox/css/jackbox.css" rel="stylesheet" type="text/css" />
  <link href="/jackbox/css/jackbox_hovers.css" rel="stylesheet" type="text/css" />

<div id="content">   
  <div class="row-title">
    <div class="container">
      <h2><?php echo utf8_encode($this->arrAgendas[0]["ag_titulo"]); ?></h2>
      <div class="breadcrumb"> <span><a href="/">Inicio</a></span> <i class="fa fa-angle-right"></i><span><a href="/agenda">Agenda</a></span><i class="fa fa-angle-right"></i><?php echo utf8_encode($this->arrAgendas[0]["ag_titulo"]); ?></div>
    </div>
  </div>
  <div class="container">

    <div class="row content-div">
        <section class="span9 ss_p_right">
          <div class="clearfix t_xs_align_c">
          <div class="photoframe type_2 shadow r_corners fleft f_sm_none d_xs_inline_b product_single_preview relative m_right_30 m_bottom_5 m_sm_bottom_20 m_xs_right_0 w_mxs_full">
            <div class="relative d_inline_b m_bottom_10 qv_preview d_xs_block">
            
              <img id="zoom_image" src="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=<?php echo RUTA_IMAGENES; ?>/<?php echo  ($this->arrAgendas[0]["ag_imagen"] != "")?$this->arrAgendas[0]["ag_imagen"]:"no_image.jpg";?>&w=450&h=450&zc=1" data-zoom-image="http://<?php echo $_SERVER["SERVER_NAME"]; ?>/imagenes/servicios/timthumb.php?src=http://admin.balneario-el-condor.com.ar/<?php echo  ($this->arrAgendas[0]["ag_imagen"] != "")?$this->arrAgendas[0]["ag_imagen"]:"no_image.jpg";?>&w=450&h=450&zc=1" class="tr_all_hover" alt="">
              
              <!-- <a href="http://admin.balneario-el-condor.com.ar/<?php echo  ($this->arrAgendas[0]["ag_imagen"] != "")?$this->arrAgendas[0]["ag_imagen"]:"no_image.jpg";?>" class="d_block button_type_5 r_corners tr_all_hover color_light p_hr_0"> -->
              
                <!-- <i class="fa fa-search-plus"></i> -->
            
            </div>
            <!--carousel-->
           
          </div>
          <div class="v_space3 t_xs_align_l shop_section">
            <!--description-->
            <h2 class="m_bottom_15 txt_trans"><?php echo utf8_encode($this->arrAgendas[0]["ag_titulo"]); ?></h2>

            <hr class="m_bottom_15 m_t_no_space">
            <table class="description_table m_bottom_15 txt-2">
              <tr>
                <td>Lugar:</td>
                <td><a href="#"><?php echo ($this->arrAgendas[0]["ag_lugar"] != "")?$this->arrAgendas[0]["ag_lugar"]:"<b>No informa</b>"; ?></a></td>
              </tr>
              <tr>
                <td>Fecha:</td>
                <td>
                <?php if ($this->arrAgendas[0]["ag_fecha"] != "")
                { echo "<a href='mailto:".$this->arrAgendas[0]["ag_fecha"]."'>" .$this->arrAgendas[0]["ag_fecha"]."</a>";}
                else{ echo "<b>No informa</b>";} ?>
                </td>
              </tr>
            </table>
            <hr class="m_bottom_15 m_t_no_space">

            </div>
          </div>
        </div>
        

        <div class="tabbable responsive shop_tabs">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#one" data-toggle="tab">Descripción</a></li>
          </ul>

          <div class="tab-content icon_tab">
            <div class="tab-pane active" id="one">

              <p class="tab_pad"><?php echo utf8_encode($this->arrAgendas[0]["ag_descripcion_corta"]); ?></p>
            
            </div>
          </div>
        </div>       
      </section>
      
    </div>         
  </div>    
</div>
    <script src="/js/elevatezoom.min.js"></script>
  <script src="/js/owl.carousel.min.js"></script>
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/es_LA/all.js"></script>


<script src="/js/jquery.isotope.js"></script>
  <script>
    jQuery(window).load(function() {  
    var jQuerycontainer = jQuery('.projects');
    //Run to initialise column sizes
    //updateSize();

    //Load masonry when images all loaded
    jQuerycontainer.imagesLoaded( function(){

        jQuerycontainer.isotope({
            // options
            itemSelector : '.element',  
            layoutMode : 'masonry',
            transformsEnabled: false,
            columnWidth: function( containerWidth ) {
                containerWidth = jQuerybrowserWidth;
                return Math.floor(containerWidth / jQuerycols);
              }
        });
    });
    
      // update columnWidth on window resize
    jQuery(window).smartresize(function(){  
        updateSize();
        jQuerycontainer.isotope( 'reLayout' );
    });

  
    //Set item size
    function updateSize() {
        jQuerybrowserWidth = jQuerycontainer.width();
        jQuerycols = 4;

        if (jQuerybrowserWidth >= 1200) {
            jQuerycols = 4;
        }
        else if (jQuerybrowserWidth >= 980 && jQuerybrowserWidth < 1200) {
            jQuerycols = 4;
        }
    
       else if (jQuerybrowserWidth >= 768 && jQuerybrowserWidth < 979) {
            jQuerycols = 4;
        }
    
    
        else if (jQuerybrowserWidth >= 401 && jQuerybrowserWidth < 767) {
            jQuerycols = 2;
        }
        else if (jQuerybrowserWidth < 400) {
            jQuerycols = 2;
        }

        //console.log("Browser width is:" + jQuerybrowserWidth);
        //console.log("Cols is:" + jQuerycols);

        // jQuerygutterTotal = jQuerycols * 20;
    jQuerybrowserWidth = jQuerybrowserWidth; // - jQuerygutterTotal;
        jQueryitemWidth = jQuerybrowserWidth / jQuerycols;
        jQueryitemWidth = Math.floor(jQueryitemWidth);

        jQuery(".element").each(function(index){
            jQuery(this).css({"width":jQueryitemWidth+"px"});             
        });
      
    
  var jQueryoptionSets = jQuery('#options .option-set'),
    jQueryoptionLinks = jQueryoptionSets.find('a');

  jQueryoptionLinks.click(function(){
  var jQuerythis = jQuery(this);
  // don't proceed if already selected
  if ( jQuerythis.hasClass('selected') ) {
    return false;
  }
  var jQueryoptionSet = jQuerythis.parents('.option-set');
  jQueryoptionSet.find('.selected').removeClass('selected');
  jQuerythis.addClass('selected');

  // make option object dynamically, i.e. { filter: '.my-filter-class' }
  var options = {},
    key = jQueryoptionSet.attr('data-option-key'),
    value = jQuerythis.attr('data-option-value');
  // parse 'false' as false boolean
  value = value === 'false' ? false : value;
  options[ key ] = value;
  if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
    // changes in layout modes need extra logic
    changeLayoutMode( jQuerythis, options )
  } else {
    // otherwise, apply new options
    jQuerycontainer.isotope( options );
  }
  
  return false;
  });   
    
    };      
    
    });
  </script>
    <script type="text/javascript" src="/jackbox/js/libs/Jacked.js"></script>
    <script type="text/javascript" src="/jackbox/js/jackbox-swipe.js"></script>
    <script type="text/javascript" src="/jackbox/js/jackbox.js"></script>
    <script type="text/javascript" src="/jackbox/js/libs/StackBlur.js"></script>
    <script>
      $(document).ready(function() {    
  jQuery(".jackbox[data-group]").jackBox("init",{deepLinking: true});
      })
    </script>
   
<script>
    FB.init({
        appId  : "341020419335849",
        status : true,
        cookie : true,
        xfbml  : true
    });
 function postToFeed(linkEnviado,pictureEnviada,tituloEnviado,descripcionEnviado) {

        // calling the API ...
        var obj = {
          method: 'feed',
          redirect_uri: 'http://www.balneario-el-condor.com.ar',
          link: linkEnviado,
          picture: pictureEnviada,
          name: tituloEnviado,
          caption: '',
          description: descripcionEnviado
        };

        function callback(response) {
        }

        FB.ui(obj, callback);
      }

       !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id)){
          js=d.createElement(s);
          js.id=id;
          js.src="https://platform.twitter.com/widgets.js";

          fjs.parentNode.insertBefore(js,fjs);
        }
      }
          (document,"script","twitter-wjs");
</script>