<section class="page-header page-header-modern bg-color-primary page-header-md ">
  <div class="container-fluid">
    <div class="row align-items-center">

      <div class="col">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <div class="overflow-hidden pb-2">
              <h1 class="text-light font-weight-bold text-9 appear-animation animated maskUp appear-animation-visible" data-appear-animation="maskUp" data-appear-animation-delay="100" style="animation-delay: 100ms;"><?php echo $this->arrServicios[0]["ser_titulo"]; ?></h1>
            </div>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-md-center appear-animation animated fadeIn appear-animation-visible" data-appear-animation="fadeIn" data-appear-animation-delay="300" style="animation-delay: 300ms;">
              <li><a class="font-weight-semibold" href="/" style="color: #e2a522;font-size: 16px;">Inicio</a></span></li>
              <li><a class="active font-weight-semibold" href="/hospedaje" style="color: #e2a522;font-size: 16px;">Servicios</a></span> <i class="fa fa-angle-right"></i><span class="active " style="color: #e2a522;font-size: 16px;"> <?php echo $this->arrServicios[0]["ser_titulo"]; ?></span></a></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>


<!--==============================content=================================-->

<div class="container pt-3 pb-2">

<div class="row">
            <div class="col-md-5 order-md-2 mb-4 mb-lg-0 appear-animation animated fadeInLeftShorter appear-animation-visible" data-appear-animation="fadeInLeftShorter" style="animation-delay: 100ms;">
              <img src="/imagenes/servicios/<?php echo  ($this->arrServicios[0]["ser_imagenes"] != "")?$this->arrServicios[0]["ser_imagenes"]:"no_image.jpg";?>" class="img-fluid" alt="">
            </div>
            <div class="col-md-7 order-2">
                <article class="post post-large">
                    <div class="post-image">
                      <a href="#" class="d-block btn  btn-outline border-0 rounded-0 font-weight-bold text-center text-6 py-5"><?php echo $this->arrServicios[0]["ser_titulo"]; ?></a>
                    </div>

                    <div class="post-content">
                      <h4><a href="" class="text-decoration-none" style="color:black">Titular:  <span style="font-size:14px ;"><i style="color:#0088CC" class="far fa-user"></i><a style="font-size:14px ;" href="#"><?php echo ($this->arrServicios[0]["ser_nombre_contacto"] != "")?$this->arrServicios[0]["ser_nombre_contacto"]:"<b>No informa</b>"; ?></a> </span></a></h4>

                      <h4><a href="" class="text-decoration-none" style="color:black">Mail:  <span style="font-size:14px ;"><i style="color:#0088CC" class="far fa-envelope"></i><a style="font-size:14px ;" href="#"> <?php echo ($this->arrServicios[0]["ser_mail_contacto"] != "")?$this->arrServicios[0]["ser_mail_contacto"]:"<b>No informa</b>"; ?></a> </span></a></h4>

                      <h4><a href="" class="text-decoration-none" style="color:black">Compartir en:</a>
                       <div >

                        <a href="https://twitter.com/share" class="twitter-share-button" data-lang="es" data-text="<?php echo $this->arrServicios[0]["ser_titulo"]; ?>: <?php echo $this->arrServicios[0]["ser_titulo"]; ?>"><img src="/imagenes/tweet-button-300x242.jpg" style="height: 18px;" /></a>

                         <a href="#" onclick="javascript:postToFeed('http://www.balneario-el-condor.com.ar/servicios/detalle/id/<?php echo $this->arrServicios[0]["ser_keyword"]; ?>','http://www.balneario-el-condor.com.ar/imagenes/servicios/<?php echo  ($this->arrServicios[0]["ser_imagenes"] != "")?$this->arrServicios[0]["ser_imagenes"]:"no_image.jpg";?>','Servicios Balneario El Condor','<?php echo $this->arrServicios[0]["ser_titulo"]; ?>');"><img src="/imagenes/fbcCompartir.jpg" style="margin-top: -9px;" /></a><br><br> 

                      </div>
                    </h4>

                    <p class="mb-1"></p>



                    <div class="post-meta">

                    </div>

                  </div>
                </article>
            </div>
          </div>
<div id="examples" class="container py-2">
    <div class="row">
      <div class="col-lg-12">
       <div class="divider divider-primary">
        <i class="fas fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="tabs tabs-primary">
                <ul class="nav nav-tabs">
                  <li class="nav-item">
                    <a class="nav-link active" href="#popularColors1" data-bs-toggle="tab">Descripción</a>
                  </li>
                </ul>
                <div class="tab-content">
                  <div id="popularColors1" class="tab-pane active">
                    <p><?php echo utf8_encode($this->arrServicios[0]["ser_descripcion"]); ?></p>
                  </div>
                 
                </div>
              </div>
</div>
</div>
      <script>
        FB.init({
          appId  : "341020419335849",
          status : true,
          cookie : true,
          xfbml  : true
        });
        function postToFeed(linkEnviado,pictureEnviada,tituloEnviado,descripcionEnviado) {

        // calling the API ...
        var obj = {
          method: 'feed',
          redirect_uri: 'http://www.balneario-el-condor.com.ar',
          link: linkEnviado,
          picture: pictureEnviada,
          name: tituloEnviado,
          caption: '',
          description: descripcionEnviado
        };

        function callback(response) {
        }

        FB.ui(obj, callback);
      }

      !function(d,s,id){
        var js,fjs=d.getElementsByTagName(s)[0];
        if(!d.getElementById(id)){
          js=d.createElement(s);
          js.id=id;
          js.src="https://platform.twitter.com/widgets.js";

          fjs.parentNode.insertBefore(js,fjs);
        }
      }
      (document,"script","twitter-wjs");
    </script>
